### ISSUE TITLE
Couldn't access swagger-ui when Javalin is configured with a given context path

### ISSUE THREAD

**Issue by pangiole-tibco** [javalin/javalin-openapi#100]
I am using version `5.1.3`

When I create and start a Javalin application with a given context path, such as in:

```java
Javalin
    .create(config -> {
        config.routing.contextPath = "example";
        config.plugins.register(new OpenApiPlugin());
        config.plugins.register(new SwaggerPlugin());
    })
    .start(8080);
```

my browser can successfully accees the OpenAPI specification at `http://localhost:8080/example/openapi` but it could not access the Swagger UI at `http://localhost:8080/example/swagger`

**Comment by pangiole-tibco** [comment]
After some investigations it seems the following line of Kotlin being the cause of this issue

https://github.com/javalin/javalin-openapi/blob/5.1.3/javalin-plugins/javalin-swagger-plugin/src/main/kotlin/io/javalin/openapi/plugin/swagger/SwaggerHandler.kt#L24

Shouldn't the `publicBasePath` be prepended with the configured context path?

**Comment by dzikoysk** [comment]
I think that custom base path should be "/example", but yes, we should support this :)
