### ISSUE TITLE
QUESTION: how to add webjars?

### ISSUE THREAD

**Issue by DerSimeon** [javalin/javalin-openapi#105]
Hey,

I jave followed the example in this repo to add the configuration for swagger, unfortunately I am not sure where to get webjars from.
Currently Swagger tries to load something from http://myip:7777/webjars the IP and Port is correct but I am not sure where I need to get the webjars stuff from. Is that an Endpoint I have to create?

Thanks alot

**Comment by dzikoysk** [comment]
It's automatically handled by Swagger/ReDoc plugin:

* https://github.com/javalin/javalin-openapi/blob/main/javalin-plugins/javalin-redoc-plugin/src/main/kotlin/io/javalin/openapi/plugin/redoc/ReDocWebJarHandler.kt

**Comment by DerSimeon** [comment]
So I need to add something into my meta-inf? for it to work?

**Comment by dzikoysk** [comment]
It's already added in Swagger & ReDoc plugins, you shouldn't be worried about it.
