### ISSUE TITLE
Openapi ignore Avro fields when serializing an object to json

### ISSUE THREAD

**Issue by YaroslavYakymenko** [javalin/javalin-openapi#108]
I use Avro schema to generate java classes used as Repsonse/Request objects. 

Before version 5.x I had the following block of code that allowed me to ignore Avro-specific internal fields:

```
      openApiOptions
          .getJacksonMapper()
          .addMixIn(SpecificRecordBase.class, JacksonIgnoreAvroSchemaMixin.class);
```

How it can be achieved in version 5.x?

**Comment by dzikoysk** [comment]
Annotation processor is using getters, not fields, by default. As long as it's pure dto object it should not contain underlying implementation details. Could you show me example of data you don't want to see?

**Comment by YaroslavYakymenko** [comment]
Yes, there is a problem that Avro generated object is not just a pure dto. It has some class hierarchy in my case it looks like this:
`public class EmailRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord`
And all data from superclasses are being serialized.

**Comment by dzikoysk** [comment]
This is for sure associated with:

* https://github.com/javalin/javalin-openapi/issues/80

And a possibility to configure annotation processor. Another thing is that I see Avro allows you to add custom annotations to generated classes, we could probably do sth like @ExcludeProperties(from = { SpecificRecord.java }) 🤔

**Comment by YaroslavYakymenko** [comment]
As a temporary workaround, I added a Dto class that mirrors necessary fields from the Avro schema

**Comment by dzikoysk** [comment]
I see, I'll take a look on that when I'll finish schema versioning issue + I'll bootstrap some basic unit tests to make sure we won't encounter any crucial regressions.

**Comment by dzikoysk** [comment]
You can try to use experimental scripting API in Groovy to programatically exclude those non-standard Avro fields, here's an example:

https://github.com/javalin/javalin-openapi/blob/9ca6b297d8fba7cd0ba71380b8a0e6a26c4482c6/openapi-annotation-processor/src/test/compile/openapi.groovy#L20-L28

This script removes `SpecificRecord#getRecord` from `EmailRequest` entity:

https://github.com/javalin/javalin-openapi/blob/9ca6b297d8fba7cd0ba71380b8a0e6a26c4482c6/openapi-annotation-processor/src/test/kotlin/io/javalin/openapi/processor/UserCasesTest.kt#L51-L82

And that's the result:

```
{
  "openapi": "3.0.3",
  "info": {
    "title": "",
    "version": ""
  },
  "paths": {
    "/gh-108": {
      "get": {
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EmailRequest"
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    }
  },
  "components": {
    "schemas": {
      "EmailRequest": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "getEmail": {
            "type": "string"
          }
        },
        "required": [
          "getEmail"
        ]
      }
    }
  }
}
```

**Comment by dzikoysk** [comment]
* https://github.com/javalin/javalin-openapi/releases/tag/5.3.0-alpha.4
