### ISSUE TITLE
Exclude dependencies of ReDoc webjar by default

### ISSUE THREAD

**Issue by Mechite** [javalin/javalin-openapi#112]
[In the wiki for the plugin](https://github.com/javalin/javalin-openapi/wiki/1.-Installation#maven) there is an exclusion defined, however on the article I was referencing when trying to use this plugin there was no exclusion, however this exclusion is required for this plugin to function correctly due to a webjar issue.

When trying to build the project without the exclusion, you encounter the issue ``ZipException opening "node-fetch-3.0.0-beta.9.jar": ZIP file can't be opened as a file system because entry "/META-INF/resources/webjars/node-fetch/3.0.0-beta.9/./@types/index.d.ts" has a '.' or '..' element in its name``. Simple fix for this issue will be to implement this exclusion directly into the plugin.

```xml
<dependency>
    <groupId>org.webjars.npm</groupId>
    <artifactId>redoc</artifactId>
    <version>2.0.0-rc.70</version>
    <exclusions>
        <exclusion>
            <groupId>*</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by dzikoysk** [comment]
This exclusion was intentionally mentioned in wiki, not sure about the article you're referencing to, but it wasn't written be me for sure. I guess we can exclude it in the plugin, but this issue will occur for people trying to change ReDoc UI version, so I just wanted to make it clear in docs.

**Comment by Mechite** [comment]
> This exclusion was intentionally mentioned in wiki, not sure about the article you're referencing to, but it wasn't written be me for sure. I guess we can exclude it in the plugin, but this issue will occur for people trying to change ReDoc UI version, so I just wanted to make it clear in docs.

https://javalin.io/tutorials/openapi-example
