### ISSUE TITLE
Add example to Body DTO

### ISSUE THREAD

**Issue by ValerioDeBlasio** [javalin/javalin-openapi#114]
Hi, 
is there a way to put an example on the body of a post request, using a DTO?

In the old version we used the following method to add an example

```
BodyDTO bodyDTOexample;

 .body(BodyDTO.class, openApiParam ->
       openApiParam.getContent().get(guessContentType(BodyDTO.class))
       .addExamples("Example", new Example().value(bodyDTOexample))
```

Thank you

**Comment by dzikoysk** [comment]
Not really, it'd require serialization, so we can't do it at compile-time. You can create sth like that using documentation processor to inject those serialized values on your own I think

**Comment by dzikoysk** [comment]
I'm closing this for now, if you'd like to add something to this topic feel free to continue this thread :)
