### ISSUE TITLE
Distinguish definitions in plugin setup

### ISSUE THREAD

**Issue by p4paul** [javalin/javalin-openapi#115]
This simple example creates two endpoints (v1 and v1.2 are deprecated and v1.3 active).  

The swagger page has a dropdown on the title bar 'Select a definition' which shows the appropriate API docs for the version.  However the 'Try it out' button is using the version specified in the OpenApiServer variable `openApiServer.addVariable("version", apiVersionVariable);`

How do I get the 'Try it out' button to use the current API version (so I can remove the OpenApiServer variable for version)?

```java
package test.javalin;

import io.javalin.Javalin;
import io.javalin.http.Context;
import io.javalin.openapi.HttpMethod;
import io.javalin.openapi.OpenApi;
import io.javalin.openapi.OpenApiContent;
import io.javalin.openapi.OpenApiResponse;
import io.javalin.openapi.OpenApiServer;
import io.javalin.openapi.OpenApiServerVariable;
import io.javalin.openapi.plugin.OpenApiConfiguration;
import io.javalin.openapi.plugin.OpenApiPlugin;
import io.javalin.openapi.plugin.swagger.SwaggerConfiguration;
import io.javalin.openapi.plugin.swagger.SwaggerPlugin;
import io.javalin.plugin.bundled.CorsPluginConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;

public class Main {

	private static final Logger LOGGER = LoggerFactory.getLogger(Main.class);

	public static void main(String[] args) {

		LOGGER.info("Starting...");

		Javalin javalin = Javalin.create(config -> {
					OpenApiServerVariable portServerVariable = new OpenApiServerVariable();
					portServerVariable.setValues(new String[]{"7070"});
					portServerVariable.setDefault("7070");

					OpenApiServerVariable hostServerVariable = new OpenApiServerVariable();
					hostServerVariable.setValues(new String[]{"localhost"});
					hostServerVariable.setDefault("localhost");

					OpenApiServerVariable apiVersionVariable = new OpenApiServerVariable();
					apiVersionVariable.setValues(new String[]{"v1", "v1.1", "v1.2", "v1.3"});
					apiVersionVariable.setDefault("v1.3");
					apiVersionVariable.setDescription("API version");

					OpenApiServer openApiServer = new OpenApiServer();
					openApiServer.setUrl("http://{host}:{port}/api/{version}");
					openApiServer.addVariable("host", hostServerVariable);
					openApiServer.addVariable("port", portServerVariable);
					openApiServer.addVariable("version", apiVersionVariable);

					OpenApiServer[] servers = new OpenApiServer[]{openApiServer};

					String deprecatedDocsPath = "/openapi";
					OpenApiConfiguration openApiConfiguration = new OpenApiConfiguration();
					openApiConfiguration.setServers(servers);
					openApiConfiguration.setDocumentationPath(deprecatedDocsPath);
					config.plugins.register(new OpenApiPlugin(openApiConfiguration));

					SwaggerConfiguration swaggerConfiguration = new SwaggerConfiguration();
					swaggerConfiguration.setUiPath("/swagger");
					swaggerConfiguration.setDocumentationPath(deprecatedDocsPath);
					config.plugins.register(new SwaggerPlugin(swaggerConfiguration));

					config.plugins.enableCors(cors -> cors.add(CorsPluginConfig::anyHost));
				})
				.get("/", ctx -> ctx.result("Hello World"))
				.start(7070);


		javalin.get("/api/v1.3/status", StatusController::getAll);
		javalin.get("/api/v1/status", StatusControllerV1::getAll);
	}

	@OpenApi(
			summary = "Get all services status",
			operationId = "getStatus",
			path = "/status",
			versions = {"v1.3"},
			methods = {HttpMethod.GET},
			tags = {"Status"},
			responses = {
					@OpenApiResponse(
							status = "200",
							content = @OpenApiContent(from = String[].class)
					)
			}
	)
	public class StatusController {
		public static void getAll(Context ctx) {
			List<String> list = new ArrayList<>();
			list.add("STATUS");
			ctx.json(list);
		}
	}


	@OpenApi(
			deprecated = true,
			summary = "Get all services status (old v1)",
			operationId = "getStatus1",
			path = "/status",
			versions = {"v1", "v1.2"},
			methods = {HttpMethod.GET},
			tags = {"Status"},
			responses = {
					@OpenApiResponse(
							status = "200",
							content = @OpenApiContent(from = Integer[].class)
					)
			}
	)
	public class StatusControllerV1 {
		public static void getAll(Context ctx) {
			List<Integer> list = new ArrayList<>();
			list.add(200);
			ctx.json(list);
		}
	}
}
```

**Comment by dzikoysk** [comment]
`Try it out` will use currently selected definition, you can see that `curl` request changes between them, e.g.:

```
    @OpenApi(
        path = "/standalone",
        methods = HttpMethod.DELETE,
        versions = "v2",
        headers = { @OpenApiParam(name = "V2") }
    )
    @OpenApi(
        path = "/standalone",
        methods = HttpMethod.DELETE,
        versions = "v1",
        headers = { @OpenApiParam(name = "V1") }
    )
```

Selected v1 definition:

![obraz](https://user-images.githubusercontent.com/4235722/205284974-a1a78f98-912c-4c99-8354-5a9bb2e422b3.png)

Selected v2 definition:

![obraz](https://user-images.githubusercontent.com/4235722/205285050-62bc115d-946b-4d37-8f35-44de741770bd.png)

In this case I don't use this `openApiServer.addVariable("version", apiVersionVariable)` and it works like that, so I think it's fine or I didn't understand this issue properly. Also, do you know if this `server.version` variable is documented somewhere?

**Comment by dzikoysk** [comment]
As I wrote this response above and checked your question once again I think you're asking if you can somehow simplify custom url using a predefined env variable with version:

```
openApiServer.setUrl("http://{host}:{port}/api/{version}");
```

Not really, because it's just regular custom variable defined by user, not specification, but seeing the intention I think it's not an issue with this particular use-case, but with the fact that our API doesn't distinguish different schema definitions (because it was implemented lately). Having a valid API, you could set url for each scheme without a need to use variable.

**Comment by dzikoysk** [comment]
Here's the updated setup:

* https://github.com/javalin/javalin-openapi/blob/14bd133f687670b024369790a703680303df195a/examples/javalin-gradle-kotlin/src/main/java/io/javalin/openapi/plugin/test/JavalinTest.java

I think that something like that covers your case:

* https://github.com/javalin/javalin-openapi/blob/14bd133f687670b024369790a703680303df195a/examples/javalin-gradle-kotlin/src/main/java/io/javalin/openapi/plugin/test/JavalinTest.java#L104

What do you think about it?

**Comment by p4paul** [comment]
Sorry I didn't reply sooner; finally got back to this project and tested out your change on 5.3.0. It works well.   

Strangely 5.3.1 seems to be missing the swagger webjars and 5.3.2 seems to be documented as released, but not on Maven Central?

**Comment by dzikoysk** [comment]
> Strangely 5.3.1 seems to be missing the swagger webjars

Are you sure that you didn't modify Swagger version in the Swagger plugin configuration?

> 5.3.2 seems to be documented as released

I didn't release 5.3.2 yet - #148

**Comment by p4paul** [comment]
Thank you for releasing 5.3.2 and helping with my use case 👍 

I don't think my issue is related to your project, but another Javalin plugin.  The Swagger pages work if I use 5.3.2 for openapi, but it fails if I upgrade ssl-plugin beyond 5.3.0?  Here is my working configuration...
```
    // Javalin
    implementation 'io.javalin:javalin-bundle:5.3.2'
    implementation 'io.javalin.community.ssl:ssl-plugin:5.3.0'

    // Javalin OpenAPI (Swagger) plugin
    def openapi = "5.3.2"
    annotationProcessor("io.javalin.community.openapi:openapi-annotation-processor:$openapi")
    implementation("io.javalin.community.openapi:javalin-openapi-plugin:$openapi")
    implementation("io.javalin.community.openapi:javalin-swagger-plugin:$openapi")
    implementation("io.javalin.community.openapi:javalin-redoc-plugin:$openapi")
```
 (BTW there is a minor bug on the [wiki](https://github.com/javalin/javalin-openapi/wiki/1.-Installation) `val openapi = "5.3.2"` needs to be  def as above)

**Comment by dzikoysk** [comment]
It works properly for me:

* `build.gradle.kts` https://github.com/dzikoysk/reposilite/blob/39554e0dbc043726bece64f8064ff4cdee4eb4a0/reposilite-backend/build.gradle.kts#L44-L48
* Implementation: https://github.com/dzikoysk/reposilite/blob/39554e0dbc043726bece64f8064ff4cdee4eb4a0/reposilite-backend/src/main/kotlin/com/reposilite/web/application/JavalinConfiguration.kt#L81-L83

>  (BTW there is a minor bug on the [wiki](https://github.com/javalin/javalin-openapi/wiki/1.-Installation) `val openapi = "5.3.2"` needs to be  def as above)

It's written in Gradle Kts :)

**Comment by p4paul** [comment]
Finally solved the gradle issue moving from ssl-plugin:5.3.0 to latest

```
shadowJar {
    minimize {
        exclude(dependency('org.eclipse.jetty.http2:http2-hpack'))
    }
    ...
}
```

Issue relates to: https://github.com/javalin/javalin-ssl/issues/59
