### ISSUE TITLE
Support `@OpenApiName` on classes

### ISSUE THREAD

**Issue by f1qwase** [javalin/javalin-openapi#122]
Hi @dzikoysk,
I think it would be helpful to make OpenApiName annotation appliable to classes as well, to have an ability to customize class names in OpenAPI spec.
API models in our project have Api prefix, (like `ApiUser`, `ApiPassport` etc.) to ditinguish them from domain models but we don't want this prefix in spec.
May be there is already a way to do this? If no, `@OpenApiName` for classes  looks like a best candidate for it.
What do you think?

**Comment by dzikoysk** [comment]
Yes, I think it might be a good idea to support this annotation on classes as well :)
