### ISSUE TITLE
Custom properties do not appear on the enum field

### ISSUE THREAD

**Issue by IvanPizhenko** [javalin/javalin-openapi#126]
I have following field declaration:
```
  @get:Schema(
    format = "key-status",
    pattern = patternStatus,
    description = "status of the key like valid|expired|revoked"
  )
  val status: Status,
```

where `Status` is enum.

With Javalin v4, with a bit different declaration:
```kotlin
  @Schema(
    type = "string",
    format = "key-status",
    pattern = patternStatus,
    description = "status of the key like valid|expired|revoked"
  )
  val status: Status,
```
(that uses Swagger annotation `Schema`), I have had following JSON:
```json
          "status": {
            "pattern": "^(valid|expired|revoked)$",
            "type": "string",
            "description": "status of the key like valid|expired|revoked",
            "format": "key-status",
            "example": null
          },
```

With v5 I only get this:
```json
          "status": {
            "$ref": "#/components/schemas/Status"
          },
```
Attributes from my custom annotation are lost.

**Comment by dzikoysk** [comment]
In general enums are now implemented as reusable enums:

* https://github.com/javalin/javalin-openapi/issues/97

The output of v4 doesn't look right, it's declared as enum so it's expected to contain an exact value, but in your snippet it expects string that follows given pattern.

**Comment by IvanPizhenko** [comment]
ok, I think this one can be closed taking into account above change.
