### ISSUE TITLE
Support OpenApi annotations defined in standalone modules

### ISSUE THREAD

**Issue by f1qwase** [javalin/javalin-openapi#128]
we store common API models shared between multiple projects in a separated `api` project

but annotations of models from that project are totally ignored by annotation processor when annotation processor runs on a project that imports `api` project (using `implementation(project(":api"))`)

I guess it may be limitation of kapt, because both Gson that uses reflection and koltlinx.serialization that is compiler plugin don't have that problem and can read their annotations from imported projects

is there a way to fix it?

thank you

**Comment by dzikoysk** [comment]
Do you mean that entity annotations:

* https://github.com/javalin/javalin-openapi/wiki/3.-Features#openapi-entities

Does not work if they're not declared in the processed module or you'd also like to support `@OpenApi` annotations used in 3rd party modules?

**Comment by f1qwase** [comment]
I mean that entity annotations don't work if they are used on a model that declared and used in another one. I have a structure like that:
```
project
  moduleX
     src
        ModelA.kt
     build.gradle.kts
  moduleY
     src
        ModelB.kt
     build.gradle.kt
  build.gradle.kts
  settings.gradle.kts
```

where files ModelA and ModelB are like
```kotlin
// ModelA.kt

@OpenApiName("NotWorking")
class ModelA
```

```kotlin
// ModelB.kt

@OpenApiName("Working")
class ModelB {
   val modelA: ModelA,
}
```

```kotlin
// settings.gradle.kts
include(
  "moduleX",
  "moduleY",
)
```

and moduleY/build.gradle.kts imports moduleY like
```kotlin
// moduleY/build.gradle.kts

dependencies(
  implementation(project(":moduleX")
)
```

if I run moduleY:kaptKotlin gradle task it produces openapi-default.json like
```json
{
   "schemas": {
      // should be "NotWorking"
      "ModelA": {
         "type": "object",
      },
      "Working" {
         "type": "object",
         "properties": {
            "modelA": {
               "$ref": "schemas/components/ModelA"
            }
         }
      }
   }
}
```

sorry for so much details, I don't understand how gradle works and might provide unnecessary details

**Comment by dzikoysk** [comment]
Could you try to use the latest snapshot? Those annotations should be preserved in compiled sources, so annotation processor should be able to find them in binary files :)

**Comment by f1qwase** [comment]
@dzikoysk I tried the latest commit (51d2405) and it works
thanks a lot!
but then I checked previous one (dd2ebd94b) with `BINARY` annotations and it works as well, so may be `BINARY` retention is enough
I guess that different testing results here and in #125 may be a result of some sort of caching so I cleaned all gralde caches I could find before testing

**Comment by f1qwase** [comment]
We use Gradle

**Comment by dzikoysk** [comment]
Ok, thanks. I think we can close it now, I'll continue to work on that in #125. If `runtime` will help, we'll leave it as it is, if not I'll revert that change to binary.

**Comment by IvanPizhenko** [comment]
I also use Gradle

**Comment by IvanPizhenko** [comment]
If keeping annotations at runtime works, then let it be.

**Comment by IvanPizhenko** [comment]
I did not test yet, but will try again soon.
