### ISSUE TITLE
Support discriminator in composition annotations

### ISSUE THREAD

**Issue by f1qwase** [javalin/javalin-openapi#129]
Union types can be described in OpenAPI with oneOf keyword.
But there is also very important oneOf property: discriminator. 

[Documentation](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/)

It allows to determine which type of union came in request/response and find a proper deserializer for it.

We use it in our specification and it works well with typescript openapi-generator which generates client code for our project.

But we still have to write this part of specification manually because it is not supported by openapi-annotation-processor.
___

As you can see in documentation, it is pretty complex property, and while `propertyName` is a pretty simple to implement with annotations, `mapping` is a bit more complex.

We use `kotlinx.serialization` in couple with sealed interfaces to produce that union types.

Considering you have a sealed interface like this:
```kotlin
@Serializable
sealed interface Union

@Serializable
data class A(val a: String) : Union

@Serializable
data class B(val b: String) : Union
```

If you serialize `A` or `B`  as Union `kotlinx.serialization` will add a property `type` with value `A` or `B` to the resulting json.
```kotlin
Json.encodeToString(Union.serializer(), A("a"))
// {"type":"A","a":"a"}
```

Names `A` or `B` can be changed with `@SerialName` annotation and default property name `type` can also be changed.

So in terms of OpenAPI `Union` type is `oneOf(A, B)` with discriminator `"type"` and mapping `A` to `A` and `B` to `B`.

___
It would be great to have an ability to generate this part of specification automatically.
I can suppose to add an optional property `discriminator` to oneOf annotation which will be used to generate discriminator property name and mapping.
And it would be great not to describe mapping inside it but to obtain it from subclasses annotations.

**Comment by dzikoysk** [comment]
For sure we should support this, but because I'm not familiar with this part in general, could you prototype usage with `OneOf` annotation and example json output that you think would fit the best your use-case? :)

**Comment by f1qwase** [comment]
The minimal code that would satisfy our needs:

```kotlin
@OneOf(
    discriminator = Discriminator(
        propertyName = "type"
    )
)
sealed interface Union

@OneOfMappingName('class-a')
data class A(val a: Int) : Union

@OneOfMappingName('class-b')
data class B(val b: String) : Union
```

to produce following OpenApi spec:

```json
{
  "schemas": {
    "Union": {
      "type": "object",
      "oneOf": [
        {
          "$ref": "#/components/schemas/A"
        },
        {
          "$ref": "#/components/schemas/B"
        }
      ],
      "discriminator": {
        "propertyName": "type",
        "mapping": {
          "class-a": "#/components/schemas/A",
          "class-b": "#/components/schemas/B"
        }
      }
    },
    "A": {
      "type": "object",
      "properties": {
        "a": {
          "type": "number"
        },
        "type": {
          "type": "string"
        }
      },
      "required": [
        "a",
        "type"
      ]
    },
    "B": {
      "type": "object",
      "properties": {
        "b": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "required": [
        "b",
        "type"
      ]
    }
  }
}
```

Note that discriminator.propertyName ("type" in this case) field must be presented and required in all subclasses
___

## Simple classes

We always use discriminator on a sealed classes/interfaces which allows to create mapping automatically because all subclasses of sealed class/interface are known at compile time, so it is possible to traverse all subclasses and get their `@OpenApiMappingName` (or throw an exception if it is not set?)
But your plugin is java compatible which means simple classes should be supported as well

So I would extend `@OneOf` from the sample above with autoMapping and mapping parameters:

```kotlin
// case one: sealed class/interface
@OneOf(
    discriminator = Discriminator(
        propertyName = "type",
        autoMapping = true // requires annotated class/interface to be sealed
    )
)
sealed interface Union


@OneOfMappingName('class-a')
data class A(val a: Int) : Union

@OneOfMappingName('class-b')
data class B(val b: String) : Union

// case two: simple class
@OneOf(
    discriminator = Discriminator(
        propertyName = "type",
        mapping = Mapping(
            ClassMapping("class-a", A::class.java),
            ClassMapping("class-b", B::class.java)
        )
    )
)
interface Union2

data class A2(val a: Int) : Union2
data class B2(val b: String) : Union2
```

**Comment by f1qwase** [comment]
You are right, discriminator can be used in `AllOf` but as I can see `mapping` property is not used in this case

In the examples I could find `allOf.discriminator` contains only `propertyType` property and mapping is made implicitly by component names (`A` and `B` in the sample above).

**Comment by dzikoysk** [comment]
As far as I see in specification it's allowed to be used with each combinator:

![obraz](https://user-images.githubusercontent.com/4235722/208736490-d61a93a6-768d-419e-9f15-13c473f2dac7.png)

~ https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#discriminatorObject

Not sure what's the use case, but I think I'll implement it like that. It'll be also easier to just the same annotations for each case.

**Comment by dzikoysk** [comment]
Implementation with output:

* https://github.com/javalin/javalin-openapi/pull/131

By default if you won't specify classes (for refs) or mappings, it'll automatically search for subclasses. If specified, the given ones are provided instead of subclasses.

I need to add 1-2 tests more, but I'll finish it tomorrow. In the meantime you can check if it makes sense for you.

**Comment by f1qwase** [comment]
Wow, cool, I'll try it in a few hours

**Comment by f1qwase** [comment]
I tried it and want to report some issues
1. automapping ignores `@OpenApiName` of subclasses, so discriminator.mapping references on class by it's simpleName while the class itself has name from `@OpenApiName`


2. according to OpenAPI documentation field with name from propertyName ("type" in our sample) must be presented in all models listed in `oneOf` and it must be required. Is it possible to add it if it is not present there already?
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/4194799/208919035-4494947a-601c-4c44-9b08-48400cda0f13.png">

**Comment by dzikoysk** [comment]
> according to OpenAPI documentation field with name from propertyName ("type" in our sample) must be presented in all models listed in oneOf and it must be required. Is it possible to add it if it is not present there already?

This is slightly problematic, because we need to generate non-existing property for class definition 🤔 Don't you think that this property should be defined in class to fulfill serialization rules? It'd be quite strange to expect this property if it'd be present in those classes, so e.g. Jackson would need to throw exception as it doesn't allow by default to serialize entities with extra properties.

**Comment by f1qwase** [comment]
I'm afraid you are right :) Silent generation of non-existing property kinda smells.
From another hand that's exactly what our serialization library (`kotlinx.serialization`) does: it injects field with model name inside json. I understand that this magic with "type" field is rather problem of `kotlinx.serializatoin` and you don't have to make your plugin compatible with all serialization libraries.

I'm just trying to find a way to make them work together. I just checked: `kotlinx.serialization` explicitly forbids the models to have the field used as discrimintor to avoid conflicts.
What about adding something like `autoInject` boolean property to @Discriminator?
Of course it makes your product more complex which is not good but I don't see any other disadvantages.
I would implement it and propose a PR if only you agree for that.

**Comment by dzikoysk** [comment]
I see, well kinda strange. Another issue I see is that we don't know the type of this discriminator property, I guess it's not always `string`? 🤔

**Comment by f1qwase** [comment]
Oh, I didn't ever think about it. And it looks like OpenAPI allows to have any type there. And it definitely make sense for enums for exapmle.

**Comment by dzikoysk** [comment]
So maybe something like `injectPropertyInMappings = DiscriminatorProperty(name = "type", type = String::class)` 🤔

**Comment by f1qwase** [comment]
it would be great!
but how is it supposed to be combined with `discriminator` property of `@OneOf`?
```kotlin
@OneOf(
    disriminator = Discriminator(propertyName = "type"),
    injectPropertyInMappings = DiscriminatorProperty(name = "type", type = String::class)
)
```
is it correct?

**Comment by dzikoysk** [comment]
I think it should be inside the `@Discriminator()` annotation as it's related to `propertyName` 🤔

**Comment by f1qwase** [comment]
like that?
```kotlin
@OneOf(
    disriminator = Discriminator(
       propertyName = "type",
       injectPropertyInMappings = DiscriminatorProperty(name = "type", type = String::class)
    )
)
```
in any case DiscriminatorProperty.name looks redundant because it must duplicate Discrimator.name
or you suppose to use `injectPropertyInMappings` without `discriminator`?
___
Regarding emiting property to scheme generator I understood you and really, I'm so embarrased to distract you on such minor things like support of  specific serialization libraries especially given the fact that it requires significant changes

I thougth I could add "type" fields with a script that post-processes OpenAPI spec as a json.
It is a hacky solution, but maybe it is fine since it is a support of `kotlix.serialization` magic and thus as any magic it doesn't have to have proper solution.

**Comment by dzikoysk** [comment]
Yeah, we can reuse value from `propertyName` 😅 

---

Btw, what would happen if you'd add this property directly to your subclasses? Also, which exactly kotlinx.serialization library do you mean, by default it just serializes data, so I guess you're using some extra generator to generate those typescript mappings?

**Comment by f1qwase** [comment]
We use https://github.com/Kotlin/kotlinx.serialization library as a serialization library on server side (and on both client/server sides when our different services communicates with each other).
It is not the most popular library, we chose it because it is offcical one and because it runs in compile time.

It also has very convinient support of polymorphism: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#sealed-classes
It implicitly adds discriminator field to json and I found it very convinient because it keeps that field on serialization level and if you use `kotlinx.serialization` on both client and server sides (which we do communicating between services) you may not think about disciminator at all: it just works.
Later when our API grown and it became difficult to keep it conistent with documentation I started to search for an instrument that could help us with it and OpenAPI was an obvious candidate which we finally chosen. And I was very happy to discover that the way kotlinx.serializtion supports polymorphism (by discriminator field) is fully compatible with OpenAPI standard.

## about the typescript mappings
We also tried to generate client API code for our typescript client and it works perfect. E.g. the sample of OpenAPI code above will produce TS code (I removed some code for short, just wanted to show the idea how it works):
```typescript
interface A {
    a: number;
    type: string;
}
interface B {
    b: string;
    type: string;
}
type Union = { type: 'class-a' } & A | { type: 'class-b' } & B;

export function UnionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Union {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'class-a':
            return {...AFromJSONTyped(json, true), type: 'class-a'};
        case 'class-b':
            return {...BFromJSONTyped(json, true), type: 'class-b'};
        default:
            throw new Error(`No variant of Union exists with 'type=${json['type']}'`);
    }
}
```
you can see it uses discriminator field to find a proper deserializer for coming object

___
Thus, after you kindly close some issues from our side all our chain:
[Kotlin models] ===javalin-openapi===>>> [OpenAPI spec] ===[openapi-generator](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-fetch.md)===>>> [TS models]
works except that moment with injecting `type` field to OpenAPI models

That's why I wrote all this wall of text :)
___
Oh, in answer to your question if I add propertyName field to models `kotlinx.serialization` will throw an error which is understandable because if he don't, data in this field will be silenlty overwritten by serialization library which is not good.

**Comment by dzikoysk** [comment]
Take a look on alpha.6, I think it should cover your use case:

* https://github.com/javalin/javalin-openapi/releases/tag/5.3.0-alpha.6

**Comment by f1qwase** [comment]
Hi dzikoysk, I'm currently on Christmas break untill eraly January, I'll try it as soon as I get back to work.
Thank you very much!

**Comment by f1qwase** [comment]
Thank you very much, it works brilliantly
I just found one typo: you use "mappings" keyword instead of correct "mapping"
For your convinience I created PR (see above) where I renamed mappings to mapping (not only in generated json spec, but everywhere for consitency), use it if you think it fixes the problem in a right way.

**Comment by dzikoysk** [comment]
Sure, it's merged and the change is available in the latest snapshot. Unfortunately I'm unable to release 5.3.0 due to several issues with Nexus & Maven Central atm with our community accounts.
