### ISSUE TITLE
Allow prefixing webjars path for swagger

### ISSUE THREAD

**Issue by javawithrocky** [javalin/javalin-openapi#130]
**Describe the feature**
Currently `webjars` path goes to `/webjars/swagger-ui`. Please allow prefixing it with a string so that swagger docs don't break when Javalin app is deployed with reverse proxy

**Additional context**
If the Javalin app is deployed with reverse proxy which prepends a context path to the URL say `/fooservice` then swagger docs break because they go to root `/` instead of `/fooservice`. Allowing prefixes for webjars will allow us to redirect it to `/fooservice/webjars` and this not break swagger docs.

**Comment by tipsy** [comment]
> @tipsy could you transfer this issue?

### ✅

**Comment by zugazagoitia** [comment]
> @tipsy could you transfer this issue?

Maybe this could be automated with an OpenApi label 🤔

**Comment by javawithrocky** [comment]
@dzikoysk Sorry, I see this issue was closed, but I do not see the resolution. What am I missing?

**Comment by dzikoysk** [comment]
This change is already available in `5.3.0-alpha.5-SNAPSHOT` and will be available in `5.3.0-alpha.5`. [Commit that closes this issue](https://github.com/javalin/javalin-openapi/commit/9f7cc7b825c6ba987fa7141ea22cb60bafd0977c) introduces `basePath` property in Swagger plugin configuration:

https://github.com/javalin/javalin-openapi/blob/9f7cc7b825c6ba987fa7141ea22cb60bafd0977c/javalin-plugins/javalin-swagger-plugin/src/main/kotlin/io/javalin/openapi/plugin/swagger/SwaggerPlugin.kt#L17-L18

And here's the example as test case scenario:

https://github.com/javalin/javalin-openapi/blob/9f7cc7b825c6ba987fa7141ea22cb60bafd0977c/javalin-plugins/javalin-swagger-plugin/src/test/kotlin/io/javalin/openapi/plugin/swagger/SwaggerPluginTest.kt#L29-L49

**Comment by javawithrocky** [comment]
Thank you @dzikoysk! Is there documentation where I can find the release cadence? I want to figure out when to expect `5.3.0` to be out in case there's resistance to using an alpha version.

**Comment by dzikoysk** [comment]
"Stable" versions are published per each official release of Javalin, but because this plugin receives significantly more updates these days, I'm releasing current versions as alphas, so users can already use non-snapshot artifacts from maven-central.

I decided to use `alpha` identifier instead of `rc`, because I want to leave room for changes between alpha releases, plugin is developed on top of the poorly documented Java API for annotation processors and covers quite complex specification. It's also worth to mention I mostly develop it on my own, so it's pretty good trade-off at this moment. Thanks to that approach users usually get what they want in a few days rather than months and for now I didn't have any reports that it's inconvenient for either party.

**Comment by javawithrocky** [comment]
That sounds like a very good strategy. How about the schedule for non-snapshot versions? 

Also, I wanted to test it out. But the latest version seems to be: `5.3.0-alpha.4`. How do I get: `5.3.0-alpha.5-SNAPSHOT` 

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/103152377/208966296-05e94203-efc2-44b1-9ffa-9adf366cc8d3.png">

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/103152377/208966572-daebb241-4f1e-4b07-b173-09a02c6a3617.png">

**Comment by dzikoysk** [comment]
I usually release alphas at the end of the day when there're changes addressed by users. As I'm still working on some changes today, it'll probably do it in the evening.

Speaking of the snapshot builds, those are available in `maven.reposilite.com/snapshots`:

* https://github.com/javalin/javalin-openapi/wiki/1.-Installation

**Comment by javawithrocky** [comment]
Thank you! Again, that makes sense and sounds like a good strategy!

**Comment by dzikoysk** [comment]
Sure, I hope it'll work properly with your reverse proxy service now :)

**Comment by ravihasija** [comment]
@dzikoysk I can verify that swagger docs are working. But `/redoc` fails for the same reason.  I will create a new ticket for the same.

**Comment by dzikoysk** [comment]
Yup, this change is not yet implemented in ReDoc. I'll take a look on that a little bit later
