### ISSUE TITLE
Allow prefixing webjars path for redoc

### ISSUE THREAD

**Issue by ravihasija** [javalin/javalin-openapi#132]
Describe the feature
Currently webjars path goes to /webjars/redoc. Please allow prefixing it with a string so that swagger docs don't break when Javalin app is deployed with reverse proxy.

Additional context
If the Javalin app is deployed with reverse proxy which prepends a context path to the URL say /fooservice then /redoc docs break because they go to root `/` instead of `/fooservice`. Allowing prefixes for `webjars` will allow us to redirect it to `/fooservice/webjars` and this not break redoc docs.

**Comment by dzikoysk** [comment]
Custom base path impl is available for ReDoc plugin in alpha.6:

* https://github.com/javalin/javalin-openapi/releases/tag/5.3.0-alpha.6
