### ISSUE TITLE
Javalin OpenApi doesn't follow @Schema or @JsonFormat for ZonedDateTime

### ISSUE THREAD

**Issue by javawithrocky** [javalin/javalin-openapi#134]
Attached is a sample project. 

Notice:

1. `startDate` which is `LocalDate` shows in the example correctly as : `"2022-12-28"`.
2. `endDate` which is `LocalDateTime` shows in the example correctly as : `"2022-12-28T20:50:31.076Z"`
3. `endDate2` which is `ZonedDateTime` does not adhere to `@Schema` or `@JsonFormat`

**Expected Result**:
`endDate2` should show up as: `"2022-12-28T20:50:31.076Z"`

![image](https://user-images.githubusercontent.com/103152377/209870809-27e2f593-3fef-4caa-8206-a550bc5025a2.png)

[javalin-kotlin-zoneddatetime-example.zip](https://github.com/javalin/javalin-openapi/files/10316388/javalin-kotlin-zoneddatetime-example.zip)

**Comment by dzikoysk** [comment]
This plugin does not support `@Schema` from Swagger Java library, take a look on this:

* https://github.com/javalin/javalin-openapi/issues/93#issuecomment-1311031735

and `@JsonFormat` from Jackson as well as this plugin generates class structure and does not serialize input/output. Anyway, you're right that `ZonedDateTime` is missing in basic types, I'm going to add this :)

As an extra note I can add, that you could use `@OpenApiPropertyType(LocalDateTime::class)` or a new custom scripting API:

https://github.com/javalin/javalin-openapi/blob/181f460edf37decb39b90cfb02e4ecddc878e79e/openapi-annotation-processor/src/test/compile/openapi.groovy#L22-L23

Might be useful in the future :)

**Comment by dzikoysk** [comment]
`ZonedDateTime` should work now like `LocalDateTime` in the latest snapshot :)

**Comment by javawithrocky** [comment]
Thank you! I can confirm that it is working with latest upgrade to snapshot version: `5.3.0-alpha.8-SNAPSHOT`

![image](https://user-images.githubusercontent.com/103152377/209986292-a3cf50a6-460d-4821-bf60-b8d161503d12.png)

**Comment by dzikoysk** [comment]
Nice :)
