### ISSUE TITLE
Json editor is not editable

### ISSUE THREAD

**Issue by javawithrocky** [javalin/javalin-openapi#135]
I would like to edit the `name` field but I can't. I have attached a project as an example. Not sure if it's a bug or my configuration is missing something

![image](https://user-images.githubusercontent.com/103152377/210447476-bc75eac4-dd54-47d1-a953-c67d4ea99919.png)

[javalin-kotlin-zoneddatetime-example.zip](https://github.com/javalin/javalin-openapi/files/10340031/javalin-kotlin-zoneddatetime-example.zip)

**Comment by dzikoysk** [comment]
Nope, the json below is in `Response` section, it means that the response should look like this for 200 result code. Why would you like to modify response scheme?

**Comment by javawithrocky** [comment]
Duhhh :( Never mind.

When I provide the `requestBody` parameter to `@OpenApi`, it works i.e. is editable.

**Comment by dzikoysk** [comment]
Well, then it's in the request section so indeed it's useful to edit, because it's easier to send different requests from UI :)
