### ISSUE TITLE
Global security not working as expected

### ISSUE THREAD

**Issue by dennisameling** [javalin/javalin-openapi#137]
Using version 5.2.0

```Kotlin
        javalinConfig.plugins.register(
            OpenApiPlugin(
                OpenApiConfiguration().apply {
                    documentationPath = "/openapi"
                    info.title = "DemoAPI"
                    info.description = "Demo description"

                    security = SecurityConfiguration().apply {
                        securitySchemes["Bearer"] = BearerAuth()
                        globalSecurity.add(Security("Bearer"))
                    }

                    servers = arrayOf(
                        OpenApiServer().apply { url = "https://example.com"; description = "Dummy server" },
                    )
                }))
```

This generates the following output:

```JSON
{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "DemoAPI",
    "description" : "Demo description",
    "version" : ""
  },
  "paths" : {
    "/beta/demo" : {
      "get" : {
        "tags" : [ ],
        "summary" : "List demo data",
        "description" : "Lists all demo data in the given date range.",
        "operationId" : "listDemoData",
        "parameters" : [ {
          "name" : "date_range_end",
          "in" : "query",
          "description" : "ISO-8601 timestamp of the last date to include in the results. This timestamp is exclusive, as opposed to date_range_start, which is inclusive. Note that there may be a maximum of 30 days between `date_range_start_utc` and `date_range_end_utc` as the response might otherwise become too large.",
          "required" : true,
          "deprecated" : false,
          "allowEmptyValue" : false,
          "schema" : {
            "type" : "string",
            "format" : "date-time",
            "example" : "2022-11-11T14:00:00Z"
          }
        }, {
          "name" : "date_range_start",
          "in" : "query",
          "description" : "ISO-8601 timestamp of the first date to include in the results. This timestamp is inclusive, as opposed to date_range_end, which is exclusive. Note that there may be a maximum of 30 days between `date_range_start_utc` and `date_range_end_utc` as the response might otherwise become too large.",
          "required" : true,
          "deprecated" : false,
          "allowEmptyValue" : false,
          "schema" : {
            "type" : "string",
            "format" : "date-time",
            "example" : "2022-11-10T14:00:00Z"
          }
        }],
        "responses" : {
          "200" : {
            "description" : "Returns list of demo data.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/REMOVED_FOR_BREVITY"
                }
              }
            }
          },
          "400" : {
            "description" : "Returns 400 if the request is invalid."
          }
        },
        "deprecated" : false,
        "security" : [ ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "REMOVED_FOR_BREVITY" : {}
    },
    "securitySchemes" : {
      "Bearer" : {
        "scheme" : "bearer",
        "type" : "http"
      }
    }
  },
  "servers" : [ {
    "url" : "https://example.com",
    "description" : "Dummy server",
    "variables" : { }
  }],
  "security" : {
    "Bearer" : [ ]
  }
}
```

Note the security section at the bottom. https://editor.swagger.io reports `Structural error at security`:

<img width="708" alt="image" src="https://user-images.githubusercontent.com/17739158/210618250-e5a52d4a-db0a-4c30-aa42-dd2e5f04f515.png">

So this...

```
 "security" : {
    "Bearer" : [ ]
  }
```

should become...

```
 "security" : [
    { "Bearer" : [ ] }
  ]
```

I guess that means that we'd need to update [this part of the code](https://github.com/javalin/javalin-openapi/blob/54d66ab75d0054fdb55a1a2423a723926958d459/javalin-plugins/javalin-openapi-plugin/src/main/kotlin/io/javalin/openapi/plugin/OpenApiPlugin.kt#L63-L65) to wrap it into a `List`. What do you think?

Also note this line in the JSON example above:

```
"security" : [ ]
```

This should be removed altogether if Global Security is set, otherwise parsers think that there's no security needed for those endpoints at all.

Happy to provide a PR if you could give me some pointers on what exactly to update 👍🏼

**Comment by dzikoysk** [comment]
Nice catch! Because this is a bug, I think we should modify security implementation to cover proper usage:

* https://github.com/javalin/javalin-openapi/blob/main/openapi-specification/src/main/kotlin/io/javalin/openapi/Security.kt

Those data classes should match OpenApi specification, because it's directly serialized by Jackson. Feel free to submit PR, but start from 5.3.0-alpha.7 as configuration received quite huge update there :)

**Comment by dennisameling** [comment]
Thanks for your blazing-fast reply! 🔥 I should have some time later this week to look into this and provide a PR. Will report back when I have an update 👍🏼

**Comment by dzikoysk** [comment]
Sure, it's important to fix it before 5.3.0 release :) For now I don't have access to Maven Central account due to several issues with their Nexus instances, so I guess we still have time until the end of this week.

**Comment by dzikoysk** [comment]
Fortunately the fix was quite simple and I didn't have to modify configuration API. It'll be available in 5.3.0 :)

**Comment by dennisameling** [comment]
Thank you! Updated to the new configuration as the old one got deprecated in 5.3.0. Everything's working as expected. Thanks again! 🚀

**Comment by dzikoysk** [comment]
Nice! :)
