### ISSUE TITLE
Sensible default operationId (like in legacy plugin)

### ISSUE THREAD

**Issue by sauterl** [javalin/javalin-openapi#151]
Apparently, we were benefitting from a sensible approach the old plugin used: If no operationId was specified, it used `<HTTP-Method><RouteCamelCased>` as `operationId` (e.g. for a GET for `/api/cat/list`, `getApiCatList()` ).

This breaks at least if using client generation with openapi-generator typescript/angular, as the default there is `<RouteCamelCased><HTTP-Method>`, resulting in e.g. `apiCatListGet`).

What are your thoughts on this? Obviously, I would prefer the old way of handling no specified operationId.

**Comment by dzikoysk** [comment]
What do you think about:

```
@OpenApi(
  operationId = AUTO
)
```

So if `AUTO` is declared, it'll generate such call? Currently if you won't specify it'll be just missing from scheme and I think we should keep it that way, having in mind `@OpenApi` annotation can be defined in different places without corresponding method for given route like in your case.

**Comment by sauterl** [comment]
I do very much like that approach. In my opinion, all the information to use for the auto generated one is given by the `@OpenApi` annotation. I'm just in the process of having a look at the code base and try to figure out how to implement this. So you might soon™️ -ish get a PR.

**Comment by sauterl** [comment]
@dzikoysk My suggestion is in #152 - feel free to adjust according your style. This quickly I was not able to setup some test cases that confirm the proper behaviour.

**Comment by sauterl** [comment]
@dzikoysk Thanks again for the almost immediate response and merging!

However, when using the new feature (by using the snapshot), I realised that there was an oversight on my part on handling path parameters. Before I fix this, I'd like to get your opinion (of for that matter, anyone's).

A path for a GET endpoint e.g. `api/v1/cat/{catId}` currently resolves with the new `AUTO_GENERATE` `operationId` to `apiV1Cat¢catId`, as one can see, the path parameter doesn't get capialised due to the [concise, but simple implementation](https://github.com/javalin/javalin-openapi/blob/main/openapi-annotation-processor/src/main/kotlin/io/javalin/openapi/processor/generators/OpenApiGenerator.kt#L288).

The legacy plugin, though, was somewhat more verbose and added the keyword `with` as a prefix to each parameter, still at their location within the path (`getApiV1CatWithCatId`).

Let's compare them (with an artifical example):

| HTTP Method | Path / Route | Plugin: `AUTO_GENERATE` | Legacy Plugin |
|----------------|---------------|------------------------------|-----------------|
| `GET`                |  `api/v1/cat/{catId}` | `getApiV1Cat{catId}` | `getApiV1CatWithCatId` |
| `PATH`            | `api/v1/cat/{catId}/collar/{collarId}/accessoire` | `pathApiV1Cat{catId}Collar{collarId}Accessoire` | `pathApiV1CatWithCatIdCollarWithCollarIdAccessoire`


Personally I'm not entirely sure whether the parameter prefix `with` is necessary, however I think the `AUTO_GENERATE` approach should at least produce something that is properly camelCased and being able to handle path parameter notation.

My question to @dzikoysk (and the community): Should `AUTO_GENERATE` result in

1. likewise the legacy plugin (path parameters prefixed `with` and camelCased e.g. `getCatWithCatId`, or
2. properly camelCased e.g. `getCatCatId`, or
3. leave it as is, e.g. `getCatcatId`

**Comment by dzikoysk** [comment]
`1.` I personally prefer `by` than `with`, but I don't have a strong opinion on that. In general I think that's the proper approach to address this issue. 
`2.` & `3.` doesn't make sense for me, no one names methods like that, so I think there's no point to do it that way.

Do

**Comment by sauterl** [comment]
Very glad you favour `1.` as well. The PR was already prepared ;-)
