### ISSUE TITLE
Support `@OpenApiCallback`

### ISSUE THREAD

**Issue by franck-malka** [javalin/javalin-openapi#156]
I am looking for the correct annotation to create a callback in the swagger using javalin

The swagger shall result in something like that
post:
      tags:
        - Admin
      summary: Add a new call flow
      operationId: addCallFlow
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
      callbacks:
        notificationDestination:
![Screenshot 2023-02-13 184344](https://user-images.githubusercontent.com/52399166/218518736-d60bbf9f-17c1-4f81-9d5a-481ca0fe87c9.png)

**Comment by dzikoysk** [comment]
Ok, I've checked in sources and indeed we don't support it yet:

https://github.com/javalin/javalin-openapi/blob/feabee778d36516136d273230f4eda6b7aa0f81c/openapi-annotation-processor/src/main/kotlin/io/javalin/openapi/processor/generators/OpenApiGenerator.kt#L184-L186

I'll add when I find some time for that, but if you want to do that feel free to submit PR :)

**Comment by dzikoysk** [comment]
This feature is available now in our latest snapshot build :)

**Comment by franck-malka** [comment]
sorry for the dumb question, but where are the snapshots built? and what
jar would i need to pull if i use the javalin bundle 4.6.7?

**Comment by dzikoysk** [comment]
Oh, this is plugin for Javalin 5.x, so unfortunately it won't work with 4.x. In general it's also not the same plugin as the one available for 4.x, because it was petty much not maintained for quite a long time and we've decided to replace it with a new approach.

**Comment by dzikoysk** [comment]
Snapshots are located in `maven.reposilite.com/snapshots` repository, take a look on the installation guide:

* https://github.com/javalin/javalin-openapi/wiki/1.-Installation

I recommend to migrate to Javalin 5.x, take a look at:
* Migration guide: https://javalin.io/migration-guide-javalin-4-to-5
* New OpenApi plugin config: https://github.com/javalin/javalin-openapi/wiki/2.-Setup

**Comment by franck-malka** [comment]
can't migrate to javalin 5 because of a limitation of sticking to java 8
will the snapshot work with javalin 4?

**Comment by dzikoysk** [comment]
Unfortunately it won't work :/ It might be a good idea to reevaluate tech stack, because Java 8 is almost 9 years old and quite a lot of dependencies moved to Java 11+, such as e.g. Jetty that is the base of Javalin.

**Comment by franck-malka** [comment]
For the callbacks,
Note that the method of the callback is not necessarily identical to the
method of the API call.

**Comment by franck-malka** [comment]
Hey

when i run my code with the SNAPSHOTs at runtime, the following class is
not resolved

Exception in thread "main" java.lang.NoClassDefFoundError:
io/javalin/openapi/plugin/OpenApiPluginConfiguration

although I believe i have all the dependencies in my project

<dependency>
            <groupId>io.javalin</groupId>
            <artifactId>javalin</artifactId>
            <version>5.3.2</version>
        </dependency>
        <dependency>
            <groupId>io.javalin.community.openapi</groupId>
            <artifactId>openapi-annotation-processor</artifactId>
            <version>5.3.3-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.javalin.community.openapi</groupId>
            <artifactId>javalin-openapi</artifactId>
            <version>5.3.3-SNAPSHOT</version>
        </dependency>
        <dependency>
        <groupId>io.javalin.community.openapi</groupId>
            <artifactId>javalin-openapi-plugin</artifactId>
            <version>5.3.3-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.javalin.community.openapi</groupId>
            <artifactId>javalin-redoc-plugin</artifactId>
            <version>5.3.3-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.javalin.community.openapi</groupId>
            <artifactId>javalin-swagger-plugin</artifactId>
            <version>5.3.3-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.javalin.community.openapi</groupId>
            <artifactId>openapi-annotation-processor</artifactId>
            <version>5.3.3-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.javalin.community.openapi</groupId>
            <artifactId>openapi-specification</artifactId>
            <version>5.3.3-SNAPSHOT</version>
        </dependency>

**Comment by dzikoysk** [comment]
Here's an example setup for Maven project:

https://github.com/javalin/javalin-openapi/blob/main/examples/javalin-maven-java/pom.xml

`OpenApiPluginConfiguration` is located in `javalin-openapi-plugin`:

* https://github.com/javalin/javalin-openapi/blob/main/javalin-plugins/javalin-openapi-plugin/src/main/kotlin/io/javalin/openapi/plugin/OpenApiConfiguration.kt#L13

Make sure your dependency is available at runtime, in IntellIJ you can check this in Maven/Gradle view:

![obraz](https://user-images.githubusercontent.com/4235722/220137227-1f5ce689-8b64-4118-bab7-2d9330f6d096.png)

**Comment by franck-malka** [comment]
Thanks

can't figure out why payloads are not documented with the new version. any
hint?
[image: image.png]

**Comment by dzikoysk** [comment]
The attached file is missing, you may need to upload it via GitHub UI. It might be also easier if you'd provide expected output, because in specification payload is referred multiple times in different schemes/parts of spec.

**Comment by franck-malka** [comment]
Ok, i think the issue is with the new jackson version and not related to
the plugin itself.
looking into it.

**Comment by dzikoysk** [comment]
This plugin does not use Jackson to describe entities like the old plugin, so it should be unrelated.

**Comment by franck-malka** [comment]
if found that if the model class has getters then it's working
but if it has public variables without getters, these fields are missing

**Comment by dzikoysk** [comment]
This is intentional behavior, because it handles by default only regular dto classes. Public fields mean you lack standardized encapsulation and as long as I recommend to change that, there's a possibility to include these properties with @OpenApiByFields annotation:

* https://github.com/javalin/javalin-openapi/wiki/3.-Features#openapi-entities

**Comment by franck-malka** [comment]
Yes, it was just working in the previous version.
In addition i found that if the model class is in another jar (in a
dependency), then the annotation is not generated as well

**Comment by franck-malka** [comment]
I think fields summary and description are missing on the callback

**Comment by dzikoysk** [comment]
> Yes, it was just working in the previous version.

There're some differences between those plugins, that's one of them. In general it's better to keep OpenApi spec independent from serialization rules, that's why we don't use Jackson at all :)

> In addition i found that if the model class is in another jar (in a
dependency), then the annotation is not generated as well

I need slightly more details about that. You should be able to use external types in your specification, even with annotations as we're keeping them even in runtime. Something you cannot do is to use `@OpenApi` annotation in dependency as annotation processor looks only for sources from current project.

> I think fields summary and description are missing on the callback

I've missed that as I didn't find it in examples in OpenApi spec & repo, but I see some people use in their examples (especially summary). I'll add both of them to the annotation, thanks :)
