### ISSUE TITLE
Generate OpenAPI specification in Gradle task

### ISSUE THREAD

**Issue by lucaro** [javalin/javalin-openapi#159]
Given that all the processing of the annotations happens during compilation, would it be possible to directly generate and export a JSON file with all specifications using, for example, a Gradle task? Most of the relevant information is already in `build/tmp/kapt3/classes/main/openapi-plugin/openapi-default.json` (or whatever version information is used), but I don't understand enough about the process of how this is generated to see how the remaining information could be added there during the build process. Any suggestions on how this could be achieved?

**Comment by dzikoysk** [comment]
For each version, there's a set of extra global properties configured through openapi plugin:

https://github.com/javalin/javalin-openapi/blob/dc33be56174a0c53cf28daafced6f0de64f35b8b/javalin-plugins/javalin-openapi-plugin/src/main/kotlin/io/javalin/openapi/plugin/OpenApiPlugin.kt#L46-L70

You'd need to somehow generate it in your Gradle task and combine it with the existing scheme 🤔
