### ISSUE TITLE
Exemples of GET with query string params

### ISSUE THREAD

**Issue by jflebeau** [javalin/javalin-openapi#163]
Hi, in the [test project](https://github.com/javalin/javalin-openapi/blob/main/examples/javalin-gradle-kotlin/src/main/java/io/javalin/openapi/plugin/test/JavalinTest.java) there is no example of a `GET` request with query string parameters, is there one somewhere?

**Comment by dzikoysk** [comment]
Yes, it works the same like the other params:

* https://github.com/javalin/javalin-openapi/blob/main/openapi-specification/src/main/kotlin/io/javalin/openapi/OpenApiAnnotations.kt#L62
