### ISSUE TITLE
Support setting description on object properties

### ISSUE THREAD

**Issue by dennisameling** [javalin/javalin-openapi#165]
As part of the OpenAPI 3 spec, it's supported to set a `description` on object properties:

```JSON
  "components" : {
    "schemas" : {
      "DummyObject" : {
        "type" : "object",
        "additionalProperties" : false,
        "properties" : {
          "dummy_property" : {
            "type" : "string",
            "format" : "date-time",
            "example" : "2022-12-30T12:00:00Z",
            "description": "Fancy description here" <-- This one
          },
          "dummy_property_two" : {
            "type" : "string",
            "format" : "date-time",
            "example" : "2022-12-30T12:15:00Z"
          },
        },
        "required" : [ "dummy_property"]
      }
  }
```

However, this library doesn't seem to support that. Please let me know if I missed something here though. I found things like `@OpenApiName`, `@OpenApiExample` and `@OpenApiPropertyType`, but couldn't find anything to set a description. I also tried with [the `@Custom` annotation which I came across in your tests](https://github.com/javalin/javalin-openapi/blob/3dad142569c29bc1a3b2855c65aed1fe7b6da350/examples/javalin-gradle-kotlin/src/main/java/io/javalin/openapi/plugin/test/JavalinTest.java#L457), but it doesn't seem to have any effect on the generated spec.

Thanks in advance! 😊

**Comment by dzikoysk** [comment]
I've added `@OpenApiDescription` annotation +  `@Custom` should work on classes as well now :)

**Comment by dennisameling** [comment]
Wow, that was fast!! Thank you so much! 🚀

**Comment by dzikoysk** [comment]
Sure, let me know if you'll experience more issues :)
