### ISSUE TITLE
JsonSchemaLoader().loadGeneratedSchemes() returns nothing

### ISSUE THREAD

**Issue by jflebeau** [javalin/javalin-openapi#169]
Hi,

I have annoted routes that show up at `/swagger` and `/openapi` but I'm not able to print generated schemas like in the exemple:
```
for (JsonSchemaResource generatedJsonSchema : new JsonSchemaLoader().loadGeneratedSchemes()) {
            System.out.println(generatedJsonSchema.getName());
            System.out.println(generatedJsonSchema.getContentAsString());
        }
```

Any idea why? If needed, I'll create a minimal exemple.

**Comment by dzikoysk** [comment]
`JsonSchemaLoader` is for entities annotated with `@JsonSchema` annotation. To load OpenApi schemes, you should use `OpenApiLoader` class.

**Comment by jflebeau** [comment]
Thanks, it worked. I should have seen the comment about JSon schemas, but I didn't came across any reference to `OpenApiLoader`.

**Comment by dzikoysk** [comment]
Sure, keep in mind that you can access all openapi schemes in OpenApiPlugin:

https://github.com/javalin/javalin-openapi/blob/main/javalin-plugins/javalin-openapi-plugin/src/main/kotlin/io/javalin/openapi/plugin/OpenApiPlugin.kt#L36-L38

So usually it's just easier to modify them through this api :)
