### ISSUE TITLE
Is there a way to nest "DTO"-based ApiContent?

### ISSUE THREAD

**Issue by jflebeau** [javalin/javalin-openapi#170]
Let's say you have a complex body like in the exemple:
```
content = {
  @OpenApiContent(from = FooDTO.class), 
  @OpenApiContent(from = BarDoto.class), 
...}
```
is there a way to nest FooDTO in `foo` and BarDTO in `bar`? (see below) I've tried with the `OpenApiContentProperty` name/type but it seems to override the from.

i.e. reponse would look like: 
```
{
   "foo":{...},
    "bar":{...}
}
```

**Comment by dzikoysk** [comment]
You should just simply create response class with those properties:

```kotlin
class ComplexRequest(
  val foo: FooDto,
  val bar: BarDto
)
```

and use this type. You can't really imitate this with annotations, but it wouldn't make much sense anyway, you need an existing structure that could represent such request/response.
