### ISSUE TITLE
Support multiple security schemes

### ISSUE THREAD

**Issue by YaroslavYakymenko** [javalin/javalin-openapi#176]
I want to configure OAuth2 and ApiKey SecuritySchemes. Users should be able to use one of the defined schemes: OAuth2 token or ApiKey.
Is it possible to use the following configuration in the javalin-openapi?
https://swagger.io/docs/specification/authentication/#multiple

If yes, I want to see some code examples, thank you.

**Comment by dzikoysk** [comment]
You can define multiple authentication methods during the setup phase:

https://github.com/javalin/javalin-openapi/blob/cdfdc9384d928987bd2d4e805b374a0addae0ea5/examples/javalin-gradle-kotlin/src/main/java/io/javalin/openapi/plugin/test/JavalinTest.java#L107-L120

And then you can use them in `security` property like that:

https://github.com/javalin/javalin-openapi/blob/cdfdc9384d928987bd2d4e805b374a0addae0ea5/examples/javalin-gradle-kotlin/src/main/java/io/javalin/openapi/plugin/test/JavalinTest.java#L151-L153

**Comment by dzikoysk** [comment]
Security is an array, you can simply define multiple annotations here:

```
security = { 
     @OpenApiSecurity(name = "BasicAuth"),
     @OpenApiSecurity(name = "BearerToken")
 },
```

**Comment by YaroslavYakymenko** [comment]
Many thanks
