### ISSUE TITLE
OpenApi Spec nullable Response

### ISSUE THREAD

**Issue by RobbenJo** [javalin/javalin-openapi#177]
Hi There,

i think there is a Bug at the "OpenApiPropertyType" anotation
i want to set my response value nullable. The only way i found is this anotaion but it don't work.

Code:
@OpenApiPropertyType(definedBy = String.class, nullability = Nullability.Nullable)

Javalin and OpenApi Version are up to date 5.4.2

**Comment by dzikoysk** [comment]
We don't have annotation for that, so you can cover it with `@Custom` that allows you to add any property to the scheme:

```
@io.javalin.openapi.Custom(name = "nullable", value = "true")
```

**Comment by RobbenJo** [comment]
Thanks for the answer
for me this doesn't work now at the first try
Yes openApi looks good
but
with it i get some hibernate exception's that he can't find my column now. I think hibernate interpret this annotation too and rename my column now to "nullable" and it can't find the original column in the database answer.
I will investigate it tomorrow.

**Comment by dzikoysk** [comment]
Hibernate uses `@javax.persistence.Column(name = "name")` to rename given property, not `@Custom` 🤔

**Comment by RobbenJo** [comment]
yes sorry maybe it's to late today :D 
it works was my fail
i will talk to my colleges tomorrow if "nullable" = "true" --> the value true as string, if it is fine.
tanks for your help

**Comment by RobbenJo** [comment]
Ok as i said it is at first ok, but with value as "String", it isn't a valid OpenApi-Spec.
Can you maybe add an optional parameter to declare the value type (as Boolean for example)?

**Comment by dzikoysk** [comment]
Oh, good point. Then it should be solved by `@CustomAnnotation` that allows you to create your own set of properties with proper support for types. Anyway, I think I can just add `@OpenApiNullable` to the api. It should be available in the latest snapshot. If you don't want to use snapshot build, you can define similar annotation in your codebase and it will work the same:

```
@Target(FUNCTION, PROPERTY_GETTER, PROPERTY_SETTER)
@Retention(RUNTIME)
@CustomAnnotation
annotation class OpenApiNullable(
    val nullable: Boolean = true
)
```

**Comment by RobbenJo** [comment]
Nice thanks this class works for me and i will test it in the next version too.
Thanks

**Comment by jflebeau** [comment]
I was wondering how to specify that a field in a response is required, but can be null, will `OpenApiNullable` be the right tool?

**Comment by jflebeau** [comment]
Hmm, thinking more about it, it won't make sense to add @NotNull to the field, so it won't be added in the required field list. Could that be achieved in another way?

**Comment by dzikoysk** [comment]
Yup, if it's annotated it'll be excluded. In theory, you can try sth like:

```
@OpenApiPropertyType(definedBy = String.class, nullability = Nullability.NOT_NULL)
@Nullable String nullable
```

Because `nullability` has priority over `@Nullable`.

**Comment by jflebeau** [comment]
Sorry, I think I was't clear. The use case I have is a required field that can be null (but not omitted), i.e. I need the field to be included in the required list, but obviously I cannot use `@NotNull` to achieve this.

**Comment by dzikoysk** [comment]
The code above should have such result tho? `String nullable` is annotated with `@Nullable`, so it's marked as nullable type in your sources, but OpenApi generator interprets it as non_null, so it's added to the `required` properties 🤔

**Comment by jflebeau** [comment]
My bad, I get it now, it's working.

**Comment by dzikoysk** [comment]
I guess we could also add some kind of new annotation like `@OpenApiRequired` to enforce the behavior without workarounds 🤔

**Comment by jflebeau** [comment]
Just to be sure, `OpenApiRequired` combined with `@OpenApiNullabe` would keep the field in the required list, but would include null values?

**Comment by dzikoysk** [comment]
Yup, `@OpenApiRequired` will simply immediately add property to list of required properties and any other combination of other properties won't affect this.
