### ISSUE TITLE
Discussion / Question: <> Support for Path Params

### ISSUE THREAD

**Issue by sauterl** [javalin/javalin-openapi#178]
Since javalin has [`<>` slash-included path routing](https://javalin.io/documentation#endpoint-handlers), I was wondering how the openapi plugin handles this? 

In particular, since I couldn't find [documentation](https://swagger.io/specification/) on OpenApi's side of things which would support this feature.

**Comment by dzikoysk** [comment]
You should define it as regular path param in OpenApi (`{}`) as it's just simply not supported by current specification. You can also mention it in the description that it's actually a wildcard parameter or do sth like `{param*}`.
