### ISSUE TITLE
OpenAPI servers 

### ISSUE THREAD

**Issue by fuuqiu** [javalin/javalin-openapi#18]
OpenAPI servers How do you configure it，Javalin

**Comment by dzikoysk** [comment]
Hi, at this moment there is no support for servers entry. How do you think we should support this?

* https://swagger.io/specification/#server-object

**Comment by fuuqiu** [comment]
package io.javalin.openapi.processor.OpenApiGenerator
fun generate(annotations: Collection<OpenApiInstance>): String {
 val info = JsonObject()
        info.addProperty("title", "{openapi.title}")
        info.addProperty("description", "{openapi.description}")
        info.addProperty("version", "{openapi.version}")
        openApi.add("info", info)
         ...
        //Missing
        openApi.add("serves", servers)
}

 Reference
 package io.swagger.v3.oas.models.OpenAPI{
       ...
       private List<Server> servers = null;

**Comment by dzikoysk** [comment]
Ok, so I've finally found some time to somehow support this function. As I'm not able currently to provide dedicated api for servers, I've made it possible to edit generated docs (#13).

```java
OpenApiConfiguration openApiConfiguration = new OpenApiConfiguration();
openApiConfiguration.setDocumentProcessor(docs -> {
    // you can add whatever you want to this document using your favourite json api
    JsonObject docsObject = new JsonParser().parse(docs).getAsJsonObject();
    // add what you need, e.g. servers
    docsObject.add('servers', new JsonObject());
    // return modified docs as a result
    return docsObject.toString();
})
// [...] register plugin
```

**Comment by fuuqiu** [comment]
This way better supports customization, which is great. But how do I use it in a javalin project, I use it according to the tutorial provided by https://javalin.io/tutorials/openapi-example, there is no entry to pass in custom'serves' configuration options

Introduced framework：https://github.com/tipsy/javalin

**Comment by dzikoysk** [comment]
This is not the same plugin, to use official Javalin plugin you need to import another library :) If you want to stay with official repo, this repository is probably not what you're looking for.

My plugin replaces the official plugin which contains various problems:

* https://github.com/tipsy/javalin/issues/1296

Here's the proper usage:

* How to download: https://github.com/reposilite-playground/javalin-openapi#setup
* Setup: https://github.com/reposilite-playground/javalin-openapi/blob/main/javalin-modules/javalin-apptest/src/main/java/io/javalin/openapi/plugin/test/JavalinTest.java
