### ISSUE TITLE
Plugin generates OpenAPI output that doesn't match spec

### ISSUE THREAD

**Issue by dennisameling** [javalin/javalin-openapi#180]
Hi! Consider the following `OpenApiInfo` configuration:

```kotlin
      javalinConfig.plugins.register(
            OpenApiPlugin(
                OpenApiPluginConfiguration()
                    .withDefinitionConfiguration { version: String, definition: DefinitionConfiguration ->
                        definition
                            .withOpenApiInfo { openApiInfo: OpenApiInfo ->
                                openApiInfo.title = "Demo"
                                openApiInfo.description = "This is a demo description."
                                openApiInfo.version = version
                            }
                    }
            )
        )
```

... which generates this output:

```json
{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "Demo API",
    "summary" : null,
    "description" : "This is a demo description.",
    "terms_of_service" : null,
    "contact" : null,
    "license" : null,
    "version" : "default"
  }
}
```

When pasting this into https://editor.swagger.io for example (or any OpenAPI spec validator), it fails on these things:
- `summary` and `terms_of_service` aren't part of the OpenAPI 3 spec
- `info.contact` and `info.license` are `null` but should either be left out completely or be objects

<img width="1751" alt="image" src="https://user-images.githubusercontent.com/17739158/231089931-036558fc-1078-4feb-bc04-bb3ac01a107a.png">

I'd expect the `null` values to be left out completely. Am I doing something wrong in my implementation?

Thanks!

**Comment by dzikoysk** [comment]
To be fair, I don't remember what was the reason behind that properties. I think it might be a good idea to filter them from scheme.

**Comment by dzikoysk** [comment]
It looks like those `summary` & `termsOfService` are a part of 3.1.0:

* https://spec.openapis.org/oas/v3.1.0#info-object
* https://swagger.io/specification/#info-object

But `terms_of_service` should be `termsOfService`.

**Comment by dennisameling** [comment]
Ah sorry, my bad indeed! Thanks a lot for looking into it 😊
