### ISSUE TITLE
Discussion: Ignoring properties

### ISSUE THREAD

**Issue by sauterl** [javalin/javalin-openapi#184]
When using javalin, one way to handle serialization / deserialization could be done by [Jackson](https://github.com/FasterXML/jackson) and thus, properties that should be ignored are annotated with `@JsonIgnore`.

Unfortunately, the openapi plugin corresponding annotation, [`@OpenApiIgnore`](https://github.com/javalin/javalin-openapi/blob/main/openapi-specification/src/main/kotlin/io/javalin/openapi/OpenApiAnnotations.kt#L162) is not applicable to `FIELD`, as `@JsonIgnore` is.

My thoughts on this are as follows:

* Is there a reason why `@OpenApiIgnore` is configured to not target `FIELD`s? And if not, could we expand the target list accordingly?
* Regarding compatibility and reduced writing, is there a way to instruct the openapi plugin to also ignore `@JsonIgnore` annotated elements?

Thanks in advance!

**Comment by dzikoysk** [comment]
Sorry for late response, I didn't notice this issue.

1. By default, OpenApi plugin reads only getters and thus fields are ignored. Do you use `@OpenApiByFields`?
2. Not really, I guess it could be possible if we'd support custom annotations, so you could create sth like:

```kotlin
@OpenApiIgnore
@JsonIgnore
annotation class IgnoreInJacksonAndOpenApi
```

or with some custom handler in our scripting API.

**Comment by sauterl** [comment]
No worries, and thanks for the reply.

No, we do not use `@OpenApiByFields`.

I guess then this might be a bug:

We do have the following setup:

```kotlin
interface IMyLittleMoreThanPojo {
 val propertyWeWantInTheApi: ISomeType
val propertyWeDontWant: IOtherType
}

data class ApiMyLittleMoreThanPojo(
 override val propertyWeWantInTheApi = ApiSomeType()
) : IMyLittleMoreThanPojo {
 @JsonIgnore
 override lateinit var propertyWeDontWant: ApiOtherType
 internal set
} : 
```

This setup then results in the following OpenApi JSON:

```json
"ApiMyLittleMoreThanPojo": {
 "type": "object",
 "additionalProperties": false,
 "properties":{
    "propertyWeWantInTheApi": {
     "$ref":"#/components/schemas/ApiSomeType"
    },
   "propertyWeDontWant":{
     "$ref":"#/components/schemas/ApiOtherType"
   }
 },
 "required":["propertyWeWantInTheApi", "propertyWeDontWant"]
}
```` 

Due to our setup, we cannot use `@OpenApiIgnore`, since `propertyWeDontWant` is a _member property with backing field_ -- it might be worthwhile to simply adjust `@OpenApiIgnore` ?

**Comment by dzikoysk** [comment]
Oh, that's a property, not a field - I thought you're using Java, not Kotlin. You should annotate this with site target, like that:

```kotlin
@get:OpenApiIgnore
val propertyWeDontWant: IOtherType
```

**Comment by sauterl** [comment]
Thanks for pointing this out! I wasn't aware of site targeted annotations and my apologies for not properly label this as a kotlin problem.

**Comment by dzikoysk** [comment]
There's a nice plugin that can simplify this btw: #171
