### ISSUE TITLE
Release 5.5.0

### ISSUE THREAD

**Issue by IvanPizhenko** [javalin/javalin-openapi#185]
Hi, I was thinking (taking into accoiunt all previous discussions) that it is supposed to release all plugins together with Javalin, but at the moment I can see Javalin is released with version 5.5.0 2 weeks ago, but OpenApi plugin is not. In the previous release of Javalin (5.2.0), plugin was released 3 days later than Javalin itself.
So should we rely on the same plugin version as Javalin, or we should assume they can be different. If they are different, are they will be always compatible?
@tipsy @dzikoysk Please explain release process and release OpenApi plugin 5.5.0 if appropriate.

**Comment by tipsy** [comment]
They are supposed to be released in sync, but I suppose something happened during the releases you mention. The community projects are ran independently from the main project, and sometimes things will come up.

I usually don't give the community much of a heads up before I make a release of the main project, but I can change that.

**Comment by dzikoysk** [comment]
5.5.0 should be now available in the Maven Central. In case of similar situations in the future, feel free to open a new issue with release request.

**Comment by IvanPizhenko** [comment]
> 5.5.0 should be now available in the Maven Central. In case of similar situations in the future, feel free to open a new issue with release request.

Thank you!

**Comment by tipsy** [comment]
Definitely, I'll be giving at least 1 week notice before any release going forward!
