### ISSUE TITLE
Java record with jakarta.validation.constraints producing unwanted $ref

### ISSUE THREAD

**Issue by mrguamos** [javalin/javalin-openapi#187]
It seems that the plugin is producing an unwanted $ref when using Java record with jakarta.validation.constraints.

```
private record Credentials(
        @NotEmpty
        String username,
        @NotEmpty
        String password) {
}
```

<img width="506" alt="Screenshot 2023-05-23 at 7 11 05 PM" src="https://github.com/javalin/javalin-openapi/assets/8675872/12bfd8b1-fd77-4d47-8435-a897c85a0a10">

**Comment by dzikoysk** [comment]
I guess it'll fail with any annotation on record's property. I'll try to take a look at it tomorrow.

**Comment by dzikoysk** [comment]
It'll be available in the next release, but can already use snapshot build to get this fix :)
