### ISSUE TITLE
Incorrect OpenAPI additionalProperties for a list object

### ISSUE THREAD

**Issue by ysavourel** [javalin/javalin-openapi#191]
It seems the openApi processor doesn't generate the correct JSON for maps that have a list has value.
(Using Javalin 5.5.0 with the OpenAPI plugin 5.5.0-1)
I have the following class:

```
public class MyData {
	private String stuff = "test-1";
	private Map<String, List<Entry>> mapOfEntries;

	@OpenApiDescription(value = "Some stuff.")
	public String getStuff() {
		return stuff;
	}
	public void setStuff(String stuff) {
		this.stuff = stuff;
	}
	@OpenApiDescription(value = "The map of entries.")
	public Map<String, List<Entry>> getMapOfEntries() {
		return mapOfEntries;
	}
	public void setMapOfEntries(Map<String, List<Entry>> mapOfEntries) {
		this.mapOfEntries = mapOfEntries;
	}
}
```

And I get the following OpenAPI output:
```
 "MyData" : {
        "type" : "object",
        "additionalProperties" : false,
        "properties" : {
          "stuff" : {
            "type" : "string",
            "description" : "Some stuff."
          },
          "mapOfEntries" : {
            "type" : "object",
            "additionalProperties" : {
              "$ref" : "#/components/schemas/Entry"
            },
            "description" : "The map of entries."
          }
        }
      }
```
As you can see the `mapOfEntries` property is defined as just a single `Entry` object instead of a list.
I believe the `additionalProperties` should be more like this:
```
...
"mapOfEntries": {
  "type": "object",
  "additionalProperties": {
    "type": "array",
    "items": {
      "$ref": "#/components/schemas/Entry"
    }
  },
  "description": "The map of entries."
}
...
```
I'm missing some additional annotation(s)?

Even if the list is a list of simple strings (`Map<String, List<String>>`) we get the property defined as just one string:
```
...
          "mapOfEntries" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "description" : "The map of entries."
          }
...
```

**Comment by dzikoysk** [comment]
The problem with OpenApi is that it's written for JS-like structures, and it's kinda weird the deeper we go. I believe that `additionalProperties` & array type are not directly documented in the spec:

* https://spec.openapis.org/oas/v3.0.1
* https://swagger.io/specification/

It looks like this is even an issue on `Swagger` side:

* https://github.com/swagger-api/swagger-core/issues/4172

Anyway, I see the problem. We could adjust that part as it seems to be supported by some codegen libs:

* https://stackoverflow.com/questions/45027428/how-to-define-hashmapstring-listobject-property-in-swagger-yml
