### ISSUE TITLE
[Question] Routes do not appear unless I use @OpenApi annotation?

### ISSUE THREAD

**Issue by TimonGisler** [javalin/javalin-openapi#198]
Hi,

In previous versions all the paths specified in Javalin automatically appeared in the swagger Ui.
Was this feature removed?
Or do I need to do something to activate this feature.

Below a screenshot showcasing what I mean. I have 2 Javalin instances.
One (the left one) following the ["new" tutorial for Javalin 5](https://github.com/javalin/javalin-openapi/wiki/1.-Installation)
And on the right the "old" tutorial that was linked:

> This plugin is also compatible with Javalin 4.x, see:
>[Javalin RFC - OpenApi plugin](https://github.com/javalin/javalin-openapi/tree/99fe1f8eb1df46a1687653bf433d082d7115d426)

![image](https://github.com/javalin/javalin-openapi/assets/49547606/7609febf-f86e-4105-b354-3258220e57d2)

In the "new" implementation the "test" route does not appear.
In the "old" implementation it does.

I also made the project with both the new and old implementation available on [github](https://github.com/TimonGisler/openapi-minimal-example) in case you want to take a look yourself.

Thanks in advance. And thanks for creating such an amazing plugin : D.

**Comment by dzikoysk** [comment]
Hi, yes, this particular feature is not ported from the old OpenApi plugin. The thing is that this plugin does most of the job at compile-time, so it's simply unaware of your runtime configuration (such as e.g. routing). Although it's not possible at compile-time, you can still add some extra data to the scheme using document processor that is invoked at runtime. Something like this:

* https://github.com/javalin/javalin-openapi/issues/49#issuecomment-1336475881
