### ISSUE TITLE
ClientCredentials flowType string with tralling space

### ISSUE THREAD

**Issue by ysavourel** [javalin/javalin-openapi#200]
I'm having trouble getting the proper behavior when using the ClientCredentials OAuth2 flow: The fields for client ID and client secret do not show up in the Swagger UI.
And I noticed that there is a trailing space in the flowType declaration of io.javalin.openapi.ClientCredentials:

```
class ClientCredentials @JvmOverloads constructor(
    val tokenUrl: String,
    override val scopes: MutableMap<String, String> = mutableMapOf()
) : OAuth2Flow<ClientCredentials> {
    override val flowType: String = "clientCredentials " <--- EXTRA SPACE HERE
}
```

It looks strange to me, and I wonder if it's the cause of my problem.

I'd love to try to fix it by creating an extended ClientCredentials class in Java where i would override the string, but ClientCredentials is final. Is there any way around this? (I'm using 5.5.0-1, but 5.6.0 has the same issue).

Thanks
-yves

**Comment by dzikoysk** [comment]
The empty space is definitely a bug. Do you use the new cfg api, or the deprecated one?

**Comment by ysavourel** [comment]
The deprecated one.

**Comment by dzikoysk** [comment]
Could you try with `5.6.2-2`
