### ISSUE TITLE
OpenAPI SecuritySchemes

### ISSUE THREAD

**Issue by franck-malka** [javalin/javalin-openapi#201]
What's the correct way to have the securityscheme included in the generated swagger?

**Comment by dzikoysk** [comment]
Currently, the security scheme section can be configured via `OpenApiPluginConfiguration`, take a look at the example module:

https://github.com/javalin/javalin-openapi/blob/4b8188a74650d62a8438edf3e9d3b7af0a2592cc/examples/javalin-gradle-kotlin/src/main/java/io/javalin/openapi/plugin/test/JavalinTest.java#L108-L125

**Comment by franck-malka** [comment]
Yes, this I understand.
But I think it should be reflected on the swagger JSON file and I believe
it's not.

Franck.

**Comment by franck-malka** [comment]
Let's say for example,i use this code
.withSecurity(new SecurityComponentConfiguration()
                                    .withSecurityScheme("OAuth2", new OAuth2
("This API uses OAuth 2 with the implicit grant flow.")
                                    .withFlow(new ImplicitFlow("
https://api.example.com/oauth2/authorize")
                                        .withScope("read_pets", "read your
pets")
                                        .withScope("write_pets", "modify
pets in your account")
                                    )
                                    .withFlow(new ClientCredentials("
https://api.example.com/credentials/authorize"))
                                )
                                .withGlobalSecurity(new Security("OAuth2")
                                    .withScope("write_pets")
                                    .withScope("read_pets"))
                                ));

then the swagger UI looks fine
[image: image.png]

but the swagger.json looks like this:

===================

{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "CAPIF Core Function",
    "description" : "3GPP TS 29.222 V18.0.0 Common API Framework for
3GPP Northbound APIs",
    "contact" : {
      "name" : "Slicce",
      "url" : "https://www.slicce.co/api-terms-of-service",
      "email" : ***@***.***"
    },
    "version" : "1.1.5"
  },
  "paths" : {
    "/api-invovation-logs/v1/{aefId}/logs" : {

....

  "security" : [ ]

  }

}

=========================

and I was expecting something like this:

=========================

{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "CAPIF Core Function",
    "description" : "3GPP TS 29.222 V18.0.0 Common API Framework for
3GPP Northbound APIs",
    "contact" : {
      "name" : "Slicce",
      "url" : "https://www.slicce.co/api-terms-of-service",
      "email" : ***@***.***"
    },
    "version" : "1.1.5"
  },

  "security" [

    {},

      {
        "oAuth2ClientCredentials": [
          "client_id"
        ]
      }

  ],
  "paths" : {
    "/api-invovation-logs/v1/{aefId}/logs" : {

....


 I think some clients don't like the fact that the security section is
missing.

-Franck.

**Comment by dzikoysk** [comment]
The code you gave:

```java
.withSecurity(new SecurityComponentConfiguration()
  .withSecurityScheme("OAuth2", new OAuth2("This API uses OAuth 2 with the implicit grant flow.")
      .withFlow(new ImplicitFlow("https://api.example.com/oauth2/authorize")
      .withScope("read_pets", "read your pets")
      .withScope("write_pets", "modify pets in your account")
  )
  .withFlow(new ClientCredentials("https://api.example.com/credentials/authorize"))
)
.withGlobalSecurity(new Security("OAuth2")
  .withScope("write_pets")
  .withScope("read_pets"))
)
```

Produces valid scheme:

![obraz](https://github.com/javalin/javalin-openapi/assets/4235722/52f4c5d7-2806-4c86-a01a-aabdcec3587d)

Make sure that you use the latest version of OpenAPI plugin & annotation processor runs on updated sources (`clean package` / `clean build`)

**Comment by franck-malka** [comment]
I use version 5.6.2-2
and I get an empty security object after clean + package

**Comment by dzikoysk** [comment]
Could you prepare a small example repository that I can clone & run to reproduce your issue?

**Comment by franck-malka** [comment]
I understand, i am just missing the security fields in the controller class
annotations
I found this example
security = {
@OpenApiSecurity(name = "BasicAuth")
}
is there a doc for oAuth2.0 specific annotations?

-Franck.

**Comment by dzikoysk** [comment]
For configuration:

* https://github.com/javalin/javalin-openapi/blob/main/openapi-specification/src/main/kotlin/io/javalin/openapi/Security.kt

For annotations:

* https://github.com/javalin/javalin-openapi/blob/main/openapi-specification/src/main/kotlin/io/javalin/openapi/OpenApiAnnotations.kt#L154-L159

That's basically all we have, and it reflects 1:1 the OpenAPI specification, so that's the best source of truth there.
