### ISSUE TITLE
javalin code generation from openapi spec file

### ISSUE THREAD

**Issue by franck-malka** [javalin/javalin-openapi#207]
Is there a way to generate javalin controller class from openapi spec file with this plugin?
If not, do you know if there is another plugin to do that?

**Comment by dzikoysk** [comment]
Not really, this project is focused on generating the spec. If you want to generate a Javalin app from the spec, it might be better to ask here, as this is the project that is focused on generating such projects:

* https://github.com/OpenAPITools/openapi-generator
