### ISSUE TITLE
OpenAPI server generator (schema-first) for Javalin

### ISSUE THREAD

**Issue by dennisameling** [javalin/javalin-openapi#208]
Hi there,

Thanks for all your work on this library!

I just wanted to inform you that I've been experimenting with schema-first code generation, and made one for Javalin: https://github.com/OpenAPITools/openapi-generator/pull/17596

It's basically the opposite approach of what this library is doing, so it takes an OpenAPI spec and generates a Javalin application from it. The PR linked above also contains a sample based on the OpenAPI generator example spec.

Please feel free to chime in there if you have any ideas or suggestions! 😊 Also, please feel free to close this issue whenever you like. Just wanted to make you aware of this.

**Comment by dzikoysk** [comment]
Nice! :) I wanted to take a look at the generator and stuff around this, but I never had a time to do this, so it's really cool to see someone from the community that is willing to pick up this topic.

Let me know if you find some stuff we can improve on the plugin side to make this generator even better (also for other targets). When the PR is merged, I guess we could reference this in the wiki section:

* https://github.com/javalin/javalin-openapi/wiki

**Comment by dzikoysk** [comment]
Because this is pinned and it's not an actual issue, I'll close this :)
