### ISSUE TITLE
Examples in OpenApiResponse

### ISSUE THREAD

**Issue by mzielinski** [javalin/javalin-openapi#213]
**Describe the feature**

It would be good to have possibility to define example response for each of OpenApiResponse

```
 responses = [
        OpenApiResponse(
            status = "200",
            description = "SUCCESS",
            content = [OpenApiContent(Response::class)]
        ),
        OpenApiResponse(
            status = "500",
            description = "UNEXPECTED_ERROR",
            content = [OpenApiContent(Response::class)]
        ),
        OpenApiResponse(
            status = "503",
            description = "SERVICE_UNAVAILABLE",
            content = [OpenApiContent(Response::class)]
        )
    ],
```

I have such content in OpenAPI specification:

![image](https://github.com/javalin/javalin-openapi/assets/4195318/7bf97d6c-fce9-481e-97ab-0643400f2449)

It would be nice to have possibly to define examples and finally have such output

![image](https://github.com/javalin/javalin-openapi/assets/4195318/2606dd5f-e5ef-4f96-9e37-cc2658defe81)

To achieve that, we need to inject `example` into `content` part

```json
 "500": {
     "description": "UNEXPECTED_ERROR",
     "content": {
         "application/json": {
             "schema": {
                 "$ref": "#/components/schemas/Response"
            },
            "example": {
                "statusCode": "500",
                 "subStatusCode:": "ERROR-CODE-500-1",
                 "statusMessage": "Unexpected Error"
            }
        }
    }
},
```

**Comment by dzikoysk** [comment]
Yes, I already had a conversation about this particular feature on our Discord server today, and it was reported an hour ago in #212 :) It should be implemented by the end of this week.
