### ISSUE TITLE
How to set optional and mandatory fields on openapi class schemas?

### ISSUE THREAD

**Issue by franck-malka** [javalin/javalin-openapi#229]
How to set optional and mandatory fields on openapi class schemas?

**Comment by dzikoysk** [comment]
By default, we're marking nullable fields as optional fields and non-nullalbe fields as required _(based on Kotlin return types or `@Nullable`/@NotNull` annotations in Java)._ If you don't like this behavior, you can put `@JsonSchema` annotation on a particular type to disable it and use `@OpenApiRequired` whenever needed: 

```
@JsonSchema(requireNonNulls = false)
data class Entity(
    val wontBeRequired: String
    @OpenApiRequired
    val willBeRequired: String
)
```

**Comment by franck-malka** [comment]
@Nullable and @NotNull is fine but it doesn't seems to work for me
Let me try the other method

**Comment by franck-malka** [comment]
for example

@JsonSchema(requireNonNulls = true)
public class measurementRequest {
    @NotNull messageType messageType; //9.2.3
    @NotNull long nrppaTransactionId; //9.2.4

fist field is still marked as optional in openapi file
second field is marked as required but not because of the annotation because it is a 'long'

**Comment by franck-malka** [comment]
@OpenApiRequired is not valid in java

**Comment by dzikoysk** [comment]
It seems to be working fine:

https://github.com/javalin/javalin-openapi/blob/3d159578951461165961e21af3460a1adb01954e/examples/javalin-gradle-kotlin/src/main/java/io/javalin/openapi/plugin/test/JavalinTest.java#L398-L402

Could you share your code for more details? :)

**Comment by franck-malka** [comment]
Umm
I see you put it on getters and setters as well
I will try

**Comment by dzikoysk** [comment]
> I see you put it on getters and setters as well

We don't support this kind of annotations on fields. There's an open ticket if you'd be interested in keeping an eye on this topic tho:

* https://github.com/javalin/javalin-openapi/issues/217
