### ISSUE TITLE
Swagger plugin doesn't work for external openapi spec

### ISSUE THREAD

**Issue by mathijs81** [javalin/javalin-openapi#231]
**Actual behavior (the bug)**
I have a javalin server that has an API and an openapi specification, but no javalin-openapi annotations. (We actually use spec-first and generate the code with openapi-generator.tech which has a javalin6 generator as part of kotlin-server).

I serve the generated openapi.yaml under `/openapi` and register `config.registerPlugin(SwaggerPlugin())`

The swagger UI doesn't load under `/swagger` and says no API found.

**Expected behavior**
Swagger UI working under /swagger

**To Reproduce**
Set up project with just swagger plugin and a server openapi file.

**Additional context**
I found a workaround. The problematic code is https://github.com/javalin/javalin-openapi/blob/7e1ec6d0ddcde6f4277bfd8088cbbc4520c453aa/javalin-plugins/javalin-swagger-plugin/src/main/kotlin/io/javalin/openapi/plugin/swagger/SwaggerPlugin.kt#L56 where `OpenApiLoader` is asked to provide all API versions.
I added a resource file `openapi-plugin/.index` with just the word `default` in it and then everything works.
It would be nice if the SwaggerPlugin config could accept the versions of the API (and maybe revert back to `default` if the openapi plugin is not active) so that this works more easily.

**Comment by dzikoysk** [comment]
Released as 6.3.1-SNAPSHOT :)
