### ISSUE TITLE
Distribute artifacts through Maven Central

### ISSUE THREAD

**Issue by dzikoysk** [javalin/javalin-openapi#26]
Currently artifacts are available here:

* https://maven.reposilite.com/#/releases/io/javalin-rfc

Source:
https://github.com/javalin/javalin-openapi/blob/85a99924027f95cfeaa39ffa6595522f1a8f7d4a/build.gradle.kts#L18-L22

**Comment by juv** [comment]
How to proceed with this issue? Can I help?

**Comment by dzikoysk** [comment]
Not really, it's something we need to resolve for whole organization, take a look at:

* https://github.com/javalin/javalin/issues/1660
