### ISSUE TITLE
Version 4.6.0 throws an error on Java 15

### ISSUE THREAD

**Issue by macabrus** [javalin/javalin-openapi#28]
`java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: kotlin/jvm/JvmInline`

is thrown on Java 15 for version 4.6.0 of this plugin. However, 4.3.0 version works just fine.

**Comment by tipsy** [comment]
Could you create a minimal example with just Javalin+Java15 which reproduces this?

**Comment by dzikoysk** [comment]
This error is mostly likely related to the old openapi module, because this plugin does not provide any kind of 4.x version. For Javalin 4.x, this plugin can be imported as follows:

```
maven { url = uri("https://maven.reposilite.com/releases") }
```

```
val openapi = "1.1.7"
kapt("io.javalin-rfc:openapi-annotation-processor:$openapi") {
    exclude(group = "ch.qos.logback")
}
implementation("io.javalin-rfc:javalin-openapi-plugin:$openapi")
```

Speaking of the old module, it's probably related to the fact that you don't have Kotlin stdlib on a classpath? 🤔

**Comment by macabrus** [comment]
Oh, so there are two modules, thanks for the heads-up. Is the one you mention the official for Javalin in the future? Will it be released to maven central?

**Comment by dzikoysk** [comment]
It'll be official openapi plugin for Javalin 5.x, as the built-in openapi module has been fully removed. The official 5.0.0 version of this plugin will be also available on Maven Central, but until then if you'd like to use it you can use my repository or jitpack.

In fact, you can even see live demo of this plugin on the same repo as originally it was written for my external project :)

* Demo: https://maven.reposilite.com/swagger/
* Sources: https://github.com/dzikoysk/reposilite/tree/main/reposilite-backend

**Comment by macabrus** [comment]
@dzikoysk  I am having a hard time understanding how are these classes supposed to show up on classpath with the two dependencies you linked, Javalin documentation only shows the old version of openapi plugin:

```java
private static OpenApiOptions getOpenApiOptions() {
        SwaggerOptions swagger = new SwaggerOptions("/docs")
            .title("My REST API");
        Info applicationInfo = new Info()
            .version("1.0")
            .description("My REST API");
        return new OpenApiOptions(applicationInfo)
            .path("/open-api.json")
            .swagger(swagger);
    }
```

**Comment by dzikoysk** [comment]
You can define any custom properties you want by processing generated content:

> ```java
> OpenApiConfiguration openApiConfiguration = new OpenApiConfiguration();
> openApiConfiguration.setDocumentProcessor(docs -> {
>     // you can add whatever you want to this document using your favourite json api
>     JsonObject docsObject = new JsonParser().parse(docs).getAsJsonObject();
>     // add what you need, e.g. servers
>     docsObject.add('servers', new JsonObject());
>     // return modified docs as a result
>     return docsObject.toString();
> })
> // [...] register plugin
> ```
