### ISSUE TITLE
[ Feature request ] OpenAPI security schema support

### ISSUE THREAD

**Issue by zjor** [javalin/javalin-openapi#29]
Please add the possibility to configure security context (https://swagger.io/docs/specification/authentication/)
This will result in showing the "Authorize" button in swagger UI and allow trying endpoints requiring authentication.

An example of how it works with Spring
<img width="686" alt="image" src="https://user-images.githubusercontent.com/695809/177564544-b239692c-eb2a-4237-8f9f-c72d64b347c4.png">

**Comment by zjor** [comment]
very much looking forward to this improvement!

**Comment by dzikoysk** [comment]
Hi, I'm a little bit busy, but you should be able to achieve this effect with custom processor, I've mentioned it here:

* https://github.com/javalin/javalin-openapi/issues/18#issuecomment-902848556

`@OpenApi` annotation already supports `security` property, so all you need is to define security scheme, e.g. this for basic auth:

```yaml
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
```

I'd be sth like:

```java
docsObject.add('components', new JsonObject());
JsonObject components = docsObject.get("components");
components.add("securitySchemes", JsonObject());
// etc.
```

**Comment by dzikoysk** [comment]
Security configuration is now a part of configuration:

https://github.com/javalin/javalin-openapi/blob/ea704ea5464230a1f6ffa15ec06534cfae5e8ad8/javalin-openapi-plugin/src/main/kotlin/io/javalin/openapi/plugin/Security.kt#L3-L6

Usage in Java:

https://github.com/javalin/javalin-openapi/blob/ea704ea5464230a1f6ffa15ec06534cfae5e8ad8/openapi-test/src/main/java/io/javalin/openapi/plugin/test/JavalinTest.java#L66-L95

results in:

![obraz](https://user-images.githubusercontent.com/4235722/183467642-3f317504-63af-4631-9ffd-08e5f4c68ffa.png)
![obraz](https://user-images.githubusercontent.com/4235722/183470077-e4f1950b-8b41-485d-a5a8-b2c07557be0a.png)
