### ISSUE TITLE
Support schema versioning

### ISSUE THREAD

**Issue by GrumpyGoslin** [javalin/javalin-openapi#39]
Hi, Sorry of this is the wrong place to ask. 

I am separating my endpoints into grouped definitions based on version (i.e. api/v1, api/v2) and thanks to [Extended OpenApiPlugin, to support multiple options](https://github.com/javalin/javalin/pull/1117) I am able to do that.

However I need to be able to link them from the Swagger UI using the "Select Definition" dropdown. 

This is done in SpringFox using multiple Docket. [Here's a screenshot example](https://www.baeldung.com/wp-content/uploads/2015/12/swagger_user_1.jpg)

I can't see if that is possible in Javalin?

**Comment by dzikoysk** [comment]
Hmm this plugin is not exactly the same as before and we don't support schema versioning yet, so it's something we need to address as first 🤔 I guess we could add an optional "versions" parameter to `@OpenApi` annotation and then provide a possibility to expose those tagged routes under different path.

**Comment by dzikoysk** [comment]
OpenApi plugin supports now multiple versions of definitions, you can name them using array property called `versions`, e.g.: 

```
versions = "v1"
```

By default all annotations use "default". The url to each version is resolved using query parameter, as follows:

```
http://localhost:8080/openapi.json - displays default scheme
http://localhost:8080/openapi.json?v=default - displays default scheme
http://localhost:8080/openapi.json?v=v1 - displays v1 etc.
```

It's also injected into Swagger UI config automatically, so you can choose any available scheme from definition list:

![obraz](https://user-images.githubusercontent.com/4235722/203123593-dae33cde-2773-44c9-9bf7-7015eaa71dd2.png)
