### ISSUE TITLE
javalin-openapi-plugin 1.1.7 is not compatible with released javalin 5.0.1

### ISSUE THREAD

**Issue by IvanPizhenko** [javalin/javalin-openapi#40]
This repo [README](https://github.com/javalin/javalin-openapi#readme) declares this is dedicated for Javalin 5. However, latest released 1.1.7 still imports `Plugin` as `import io.javalin.core.plugin.Plugin` while in Javalin 5.0.1 it is `import io.javalin.plugin.Plugin`. Please release new version with proper imports.

**Comment by dzikoysk** [comment]
1.1.7 is for Javalin 4.x, for Javalin 5.x use 5.0.0-SNAPSHOT from snapshot releases. There are 2 snippets in the README for Maven/Gradle. I'm waiting for #26 with stable release.

**Comment by IvanPizhenko** [comment]
Thank you, I will try it, but generally I'd prefer to have release 5.0.0 even from your repo.

**Comment by dzikoysk** [comment]
Sure, I can do that within an hour :)

**Comment by dzikoysk** [comment]
Done, I've released 5.0.0 & 5.0.1 to match latest releases of main codebase.

**Comment by IvanPizhenko** [comment]
Thank you!
