### ISSUE TITLE
Package structure does not match group id

### ISSUE THREAD

**Issue by Playacem** [javalin/javalin-openapi#42]
Group Id: `io.javalin.community.openapi`
package structure: `io.javalin.openapi.plugin`

This confused me while updating the javalin 5 openapi example, especially as the ssl-plugin has a matching package structure to group id: `io.javalin.community.ssl`

Adding to the confusion: `OpenApiConfiguration#setTitle` as described in the example in the readme does not exist.

**Comment by tipsy** [comment]
> Package structure is backwards compatible with the old plugin and I don't really see any particular reason to change that to community just because of the distribution we've end up with + it'd be pretty breaking change for current users 🤔

Just want to weigh in and say that I agree with this. It's my bad for putting this off until after the release, maybe we can fix it next time.

**Comment by Playacem** [comment]
Well, now its kinda documented with this ticket. PR for the outdated README coming soon (tm)
