### ISSUE TITLE
Ignore some routes

### ISSUE THREAD

**Issue by lucaro** [javalin/javalin-openapi#65]
I'm in the process of migrating a project over from javalin 4 to 5. In the previous OpenAPI generator version, it was possible to exclude some routes from the generated JSON. We were using this to generate two different OpenAPI definitions where one would only include a subset of endpoints relevant for a specific type of client. Is it also possible to do this somehow in this version?

**Comment by dzikoysk** [comment]
There's no such built-in feature, but you can always process stored openapi documentation using document processor:

https://github.com/javalin/javalin-openapi/blob/3e26ab1f4b54a720526e5cb59a6da6a027df25ec/examples/javalin-gradle-kotlin/src/main/java/io/javalin/openapi/plugin/test/JavalinTest.java#L128-L131

To e.g. remove/add entries, do you think it would be enough for your case, or do you have something else in mind?

**Comment by lucaro** [comment]
Hey, thanks for the quick reply! I think the document processor should be sufficient for my needs.

**Comment by dzikoysk** [comment]
Sure, let me know if you won't be able to achieve sane result with this approach, maybe we'll figure out alternative solution.

**Comment by dzikoysk** [comment]
Fair point, the adjustment should be available in the 5.1.2-SNAPSHOT from `maven.reposilite.com/snapshots` repo when CI will finish all tasks.

**Comment by dzikoysk** [comment]
Nice!

**Comment by macabrus** [comment]
Just wanted to point out that there is "ignore=true" parameter in @OpenApi annotation which would exclude it from being generated. I tested it and works in my case.

**Comment by lucaro** [comment]
Indeed there is. This option however would remove a path from any OpenAPI spec. In case you want to have multiple definitions, each only containing a subset of all available paths, you still need some kind of filter.
