### ISSUE TITLE
Support enums

### ISSUE THREAD

**Issue by sauterl** [javalin/javalin-openapi#66]
Hi there

First of all thank you for the great work! I do have a question regarding the handling of enums though:

In our code-base, we have something like 

```kotlin
data class UserDetails(val id: String, val username: String, val role: Role, val sessionId: String? = null)
enum class Role { ANYONE, VIEWER, PARTICIPANT, JUDGE, ADMIN }
```

which [the legacy openapi plugin](https://github.com/javalin/javalin/tree/javalin-4x/javalin-openapi) projected to the following JSON OpenAPI Specification snippet:

```json
"UserDetails" : {
        "required" : [ "id", "role", "username" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          },
          "username" : {
            "type" : "string"
          },
          "role" : {
            "type" : "string",
            "enum" : [ "ADMIN", "JUDGE", "VIEWER", "PARTICIPANT" ]
          },
          "sessionId" : {
            "type" : "string"
          }
        }
      }
```

However, this plugin produced the following:

```json
"UserDetails" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          },
          "username" : {
            "type" : "string"
          },
          "role" : {
            "$ref" : "#/components/schemas/Role"
          },
          "sessionId" : {
            "type" : "string"
          }
        },
        "required" : [ "id", "username", "role" ]
      },
     "Role" : {
        "type" : "object",
        "properties" : { }
      },
```

Thus my question: How are we expected to handle enums with the new plugin? I did not find this case in the [test](https://github.com/javalin/javalin-openapi/blob/main/examples/javalin-gradle-kotlin/src/main/java/io/javalin/openapi/plugin/test/JavalinTest.java)

Thanks in advance for a reply

**Comment by dzikoysk** [comment]
Sorry for late response, I was quite busy lately. Atm it looks like we don't have dedicated support for enums, I'll try to take a look on that tomorrow :)

**Comment by dzikoysk** [comment]
It's now supported in 5.1.2 :)

**Comment by sauterl** [comment]
This was amazingly fast, thanks a lot!
