### ISSUE TITLE
Attempt to get OpenApi JSON returns 404

### ISSUE THREAD

**Issue by IvanPizhenko** [javalin/javalin-openapi#68]
I am initializing Javalin as follows:

```kotlin
  var javlin = Javalin.create { config ->
    ...
    config.plugins.register(createOpenApiPlugin())
    ...
  }

  javalin.start()

  ...

  private fun createOpenApiPlugin(): OpenApiPlugin = OpenApiPlugin(
    OpenApiConfiguration().apply {
      info = OpenApiInfo().apply {
        title = "Application Name"
        summary = "Application Name API"
        description = "Application Name API"
        termsOfService = "https://example.com/terms"
        contact = OpenApiContact().apply {
          name = "Contact name"
          url = "https://example.com/contact"
          email = "contact@example.com"
        }
        version = Product.version
      }
      documentationPath = "/openapi.json"
    }
```

Later on, I am trying to get Open API JSON with Fuel:

```kotlin
  val port = javalin.port()
  val (_, _, result) = Fuel.get("http://localhost:$port/openapi.json").response()
```

and getting exception with 404 Not Found.

What am I doing wrong?

**Comment by IvanPizhenko** [comment]
Looks like issue in my SSL certificate, new Jetty has stronger validation.

**Comment by dzikoysk** [comment]
Good to know!

**Comment by IvanPizhenko** [comment]
Sorry, mixed up with another issue. Reopening. Still face this issue. Any ideas are welcome.

**Comment by dzikoysk** [comment]
Are you sure the openapi endpoint is registered?

https://github.com/javalin/javalin-openapi/blob/main/javalin-plugins/javalin-openapi-plugin/src/main/kotlin/io/javalin/openapi/plugin/OpenApiPlugin.kt#L82

**Comment by IvanPizhenko** [comment]
I've set a breakpoint at that line and it wasn't hit. When this `apply()` should be called?

**Comment by IvanPizhenko** [comment]
So what I have found:
- `Plugin.apply()` is only called in the `PluginUtil.attachUtils()`
-  `PluginUtil.attachUtils()` is only called in the `JavalinConfig.applyUserConfig()`.
- `JavalinConfig.applyUserConfig()` is never called and not mentioned in your example.

**Comment by IvanPizhenko** [comment]
This condition: 
```kotlin
        if (documentation == null) {
            logger.warn("OpenApi documentation not found")
            return
        }
```
is not met.

**Comment by IvanPizhenko** [comment]
In the example in README it is said:
```kotlin
    // For Java projects
    annotationProcessor("io.javalin.community.openapi:openapi-annotation-processor:$openapi")
    // For Kotlin projects
    kapt("io.javalin.community.openapi:openapi-annotation-processor:$openapi")
```
My project is in Kotlin, but I can't write `kapt(...)` because gradle doesn't resolve it, so I've written `annotationProcessor(...)`. I have Gradle 7.5.1 and use Kotlin 1.7.20.

**Comment by dzikoysk** [comment]
You may need to explicitly enable kapt in your build, like that:

* https://github.com/dzikoysk/reposilite/blob/main/reposilite-backend/build.gradle.kts#L25

Then you should be able to use it:

* https://github.com/dzikoysk/reposilite/blob/main/reposilite-backend/build.gradle.kts#L81

**Comment by IvanPizhenko** [comment]
Thank you! That has worked.
