### ISSUE TITLE
OpenApi plugin throws exception when running kaptKotlin Gradle task

### ISSUE THREAD

**Issue by IvanPizhenko** [javalin/javalin-openapi#78]
**Version:** 5.1.3
**Exception information:**
```
[INFO] Processing types with annotation processors: 
error: class java.lang.IndexOutOfBoundsException: Index: 0, Size: 0  jdk.compiler/com.sun.tools.javac.util.List.get(List.java:490)
    io.javalin.openapi.processor.utils.TypesUtils.toModel(TypesUtils.kt:82)
class java.lang.IndexOutOfBoundsException: Index: 0, Size: 0  jdk.compiler/com.sun.tools.javac.util.List.get(List.java:490)

    io.javalin.openapi.processor.utils.TypesUtils.toModel$default(TypesUtils.kt:71)
    io.javalin.openapi.processor.OpenApiGenerator.addSchema(OpenApiGenerator.kt:362)
    io.javalin.openapi.processor.OpenApiGenerator.addSchema$default(OpenApiGenerator.kt:361)
    io.javalin.openapi.processor.OpenApiGenerator.fromParameter(OpenApiGenerator.kt:293)
    io.javalin.openapi.processor.OpenApiGenerator.generate(OpenApiGenerator.kt:94)
    io.javalin.openapi.processor.OpenApiAnnotationProcessor.process(OpenApiAnnotationProcessor.kt:50)
    org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
    org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:197)
....
```

**Comment by dzikoysk** [comment]
Interesting, could you use 5.1.4-SNAPSHOT, so we can get more up-to-date exception? :)

**Comment by IvanPizhenko** [comment]
I have some problem with Gradle when I've tried to switch version to `5.1.4-SNAPSHOT`:
```
Could not GET 'https://splunk.jfrog.io/splunk/ext-releases-local/io/javalin/community/openapi/openapi-annotation-processor/5.1.4-SNAPSHOT/openapi-annotation-processor-5.1.4-SNAPSHOT.pom'. Received status code 409 from server: Conflict
Disable Gradle 'offline mode' and sync project
```

**Comment by dzikoysk** [comment]
You have to declare our snapshots repository:

```
repositories {
    // For snapshots
    maven { url 'https://maven.reposilite.com/snapshots' }
}
```

Them it should be fine :)

**Comment by IvanPizhenko** [comment]
More up-to-date exception:
```
[INFO] Processing types with annotation processors: 
error: class java.lang.IndexOutOfBoundsException: Index: 0, Size: 0  jdk.compiler/com.sun.tools.javac.util.List.get(List.java:490)
class java.lang.IndexOutOfBoundsException: Index: 0, Size: 0  jdk.compiler/com.sun.tools.javac.util.List.get(List.java:490)

    io.javalin.openapi.processor.shared.JsonTypes.toModel(JsonTypes.kt:85)
    io.javalin.openapi.processor.shared.JsonTypes.toModel$default(JsonTypes.kt:74)
    io.javalin.openapi.processor.OpenApiGenerator.createTypeDescriptionWithReferences(OpenApiGenerator.kt:312)
    io.javalin.openapi.processor.OpenApiGenerator.fromParameter(OpenApiGenerator.kt:241)
    io.javalin.openapi.processor.OpenApiGenerator.generateSchema(OpenApiGenerator.kt:117)
    io.javalin.openapi.processor.OpenApiGenerator.generate(OpenApiGenerator.kt:45)
    io.javalin.openapi.processor.OpenApiAnnotationProcessor.process(OpenApiAnnotationProcessor.kt:43)
    org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
    org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:197)
....
```

**Comment by IvanPizhenko** [comment]
In the 5.1.3 (as you pointed) it was this line of code:
```
types.isAssignable(types.erasure(this), collectionType.asType()) -> typeArguments[0]?.toModel(generics, ARRAY)
```
But I just can't get where from this `typeArguments` comes from? It is never declared or imported, it is just used.

**Comment by IvanPizhenko** [comment]
Therefore this code likely need to track through the inheritance hierarchy down to `Collection<E>` and take its type argument. Is that possible?

**Comment by IvanPizhenko** [comment]
Note: I'm upgrading existing code from Javalin 4 to Javalin 5. In Javalin 4 this code uses built-in OpenApi plugin and doesn't have issue like this. Maybe you can look into code of Javalin 4 built in plugin to find out how to solve this more correctly.

**Comment by GotoFinal** [comment]
> Therefore this code likely need to track through the inheritance hierarchy down to `Collection<E>` and take its type argument. Is that possible?

It is possible, but tracking the type thro the generic hierarchy can be quite complicated and confusing, generics are really trickly when you go deep, I've once written pretty detailed explanation on stackoverflow about following generic types while supporting all the cases I could think of (with 1 exception with nested classes that have generic type references between them: https://github.com/gregorycallea/generics-utils/blob/master/src/test/java/com/github/gregorycallea/generics/GenericsUtilsTest.java#L293), that ended up in a small library that allows to fetch any generic type from any type from any other type point of view
https://stackoverflow.com/a/60299767/4378853

**Comment by IvanPizhenko** [comment]
@dzikoysk you probably really can use that library from @GotoFinal as example to write your own code to resolve type parameters.

**Comment by IvanPizhenko** [comment]
New 5.1.4-SNAPSHOT works. Please release 5.1.4. But also, if possible, please include one more small thing, please see #85.
