### ISSUE TITLE
Tag releases in Github

### ISSUE THREAD

**Issue by IvanPizhenko** [javalin/javalin-openapi#79]
It would be nice to have tags in this repo which correspond to released versions of plugin. Currently there are no any tags/releases in this repo... Can start with next version if it is hard to put tag on the existing ones.

**Comment by IvanPizhenko** [comment]
Please at least do 2 things:
- before release, merge code that you release into `main`
- put tag and push it just using `git tag vX.Y.Z; git push origin vX.Y.Z`

No need to make release with description if you don't have enough time, but cleanly designate code that you release with a tag. This way others can discover actual source code of the released version, analyze it and point you to reasons of issues like I've posted https://github.com/javalin/javalin-openapi/issues/78. Now source code of version 5.1.3 just cannot be found...

**Comment by dzikoysk** [comment]
5.1.3 is specific, because there was a typo in artifact version, so 5.1.2 == 5.1.3, sources:

* https://github.com/javalin/javalin-openapi/tree/ce14c9870762b812283697179c87ba79a9c25b2c

**Comment by IvanPizhenko** [comment]
Thank you, I will have a look.
