### ISSUE TITLE
Parameters of the API call must be sorted alphabetically.

### ISSUE THREAD

**Issue by IvanPizhenko** [javalin/javalin-openapi#86]
Parameters must be sorted alphabetically. Example (difference with Javalin 4):
[new.json.txt](https://github.com/javalin/javalin-openapi/files/9980661/new.json.txt)
[old.json.txt](https://github.com/javalin/javalin-openapi/files/9980663/old.json.txt)

**Comment by dzikoysk** [comment]
Both changes should be already available in the latest snapshot :)

**Comment by IvanPizhenko** [comment]
Thanks, I'll try it.

**Comment by IvanPizhenko** [comment]
Did you really publish it? I don't see any changes. I'll even tried `./gradlew --refresh-dependencies`, no effect.

**Comment by dzikoysk** [comment]
Yes, we have snapshot per each commit, you can check GitHub Actions to see results. If you use IntelliJ, I recommend to use this option to force update:

![obraz](https://user-images.githubusercontent.com/4235722/201206298-5a7020f6-7fa1-4214-ac79-6907a1bc12a9.png)

Running just `--refresh-dependencies` is not always enough for Gradle + IJ, so I'd give it a try.
