### ISSUE TITLE
requestBody in POST method does not conform to OpenApiV3 spec

### ISSUE THREAD

**Issue by IvanPizhenko** [javalin/javalin-openapi#88]
In the:
```json
"post": {
...
}
```

With Javalin 4 I have:
```json
        "requestBody": {
          "description": "Empty JSON",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Unit"
              }
            }
          }
        },
```

With Javalin 5 + OpenApi plugin I get:
```
        "requestBody": {
          "description": "Empty JSON",
          "content": {
            "application/json": {
              "schema": {
                "type": "application/json"
              }
            }
          },
          "required": false
        },
```

Later on I can't parse this JSON with OpenAPIV3 parser.
Some corresponding defintions from OpenAPIV3 parser (in Typescript):
```typescript
    // this one correspond to the whole object under "post"
    export type OperationObject<T extends {} = {}> = Modify<OpenAPIV3.OperationObject<T>, {
        parameters?: (ReferenceObject | ParameterObject)[];
        requestBody?: ReferenceObject | RequestBodyObject; // <<< THIS IS "requestBody"
        responses?: ResponsesObject;
        callbacks?: Record<string, ReferenceObject | CallbackObject>;
        servers?: ServerObject[];
    }> & T;

    export type RequestBodyObject = Modify<OpenAPIV3.RequestBodyObject, {
        content: {
            [media: string]: MediaTypeObject;
        };
    }>;

   // This one is the one which previous one is based on
    interface RequestBodyObject {
        description?: string;
        content: {
            [media: string]: MediaTypeObject;
        };
        required?: boolean;
    }

    interface MediaTypeObject {
        schema?: ReferenceObject | SchemaObject;
        example?: any;
        examples?: {
            [media: string]: ReferenceObject | ExampleObject;
        };
        encoding?: {
            [media: string]: EncodingObject;
        };
    }

    type SchemaObject = ArraySchemaObject | NonArraySchemaObject;

    interface ArraySchemaObject extends BaseSchemaObject {
        type: ArraySchemaObjectType;
        items: ReferenceObject | SchemaObject;
    }

    interface NonArraySchemaObject extends BaseSchemaObject {
        type?: NonArraySchemaObjectType;
    }

    type NonArraySchemaObjectType = 'boolean' | 'object' | 'number' | 'string' | 'integer';
    type ArraySchemaObjectType = 'array';

```
So in here:
```type
            "application/json": {
              "schema": {
                "type": "application/json"
              }
            }
```
"type" cannot be "application/json", it may be absent, if you generate `NonArraySchemaObject` or be one of listed in the `NonArraySchemaObjectType`, or it must be `array` if you generate `ArraySchemaObject`.

As you can see, in Javalin 4, for empty body it was generating `ReferenceObject` and mapped type to specially added type Unit.
This may be not ideal, but far more correct than what new plugin does now. Please fix this.

**Comment by dzikoysk** [comment]
Output from Javalin 4 also doesn't seem to be correct, it's basically covered by Kotlin's Unit type, so scheme might be correct, but it doesn't make any sense semantically. Could you share your `requestBody` definition from sources?

**Comment by IvanPizhenko** [comment]
```kotlin
  requestBody = OpenApiRequestBody([OpenApiContent(type = "application/json")], description = "Empty JSON"),
```

**Comment by IvanPizhenko** [comment]
> Output from Javalin 4 also doesn't seem to be correct, it's basically covered by Kotlin's Unit type, so scheme might be correct, but it doesn't make any sense semantically. Could you share your `requestBody` definition from sources?

As I said it is not a best solution, but still - schema is correct, and that's very important.

**Comment by dzikoysk** [comment]
Ok, I know why it happens, we use the same method to generate scheme for `reuqestBody` and `responses`. Such format is valid for `responses`, but not for `requestBody`. Kinda strange, but I'll just remove simple types from `resutedBody` so it'll contain scheme with reference or it'll be just empty.

**Comment by IvanPizhenko** [comment]
Please also add a unit test for this. If don't have unit tests at all, it's good time to start writing them at least for something...

**Comment by dzikoysk** [comment]
I'm maintaining several projects and I don't have enough time to address this issue at this moment:

* https://github.com/javalin/javalin-openapi/issues/74

Unit tests would protect us from regression, but not from this kind of issue that are simplify a misunderstanding of specification. It's also good to note that current schema is already processed by Swagger Validator, but we simply miss all combinations of properties in `JavalinTest.class`.

**Comment by IvanPizhenko** [comment]
Yes, that's exactly the point, users, including me, want to be protected from regressions. We use your library in our software and deliver our software to our important customers, and so want to be sure we depend on the more-less reliable software, as long as you are in active development, and your code is refactored often, and so there is higher chance to break something.

**Comment by dzikoysk** [comment]
Both usages:

```
@OpenApiContent(type = "application/json")
@OpenApiContent(mimeType = "application/json"), 
```

are now generated with empty body:

![obraz](https://user-images.githubusercontent.com/4235722/201216520-70e49b11-44e1-464d-a7b3-e1f5ed6a5b9a.png)

To be fair such usage was not intended, it's more likely a side-effect of the old OpenApi plugin, but it's not harmful so we can support this in such form.

**Comment by IvanPizhenko** [comment]
Thank you!
