### ISSUE TITLE
support for `@OneOf`  and `@Custom` in OpenAPI schemas

### ISSUE THREAD

**Issue by f1qwase** [javalin/javalin-openapi#90]
Support for `oneOf` for JsonSchema was added recently as well as support for custom properties (with `@Custom` annotation)

Are there any plans to add the same things to OpenAPI Schema?

We use OpenAPI specification to generate client code with openapi-generator so we can't use JsonSchema specs (referencing JsonSchema files from OpenAPI spec is possible since OpenAPI 3.1 but 3.1 version is not supported by openapi-generator yet).

It would be great to use `@Custom` annotations in OpenAPI schema to set properties like "pattern", "example" and so on.
I would try to help with it and make PR if these things are needed in your project (I believe they are since they are part of OpenAPI spec).

**Comment by dzikoysk** [comment]
Those properties should work in OpenApi generator as well, because @OpenApi & @JsonScheme annotations use the same underlying TypesGenerator.

**Comment by f1qwase** [comment]
Thank you very much

I finally found why it didn't work for me
It's because I used these annotations (`@OneOf`, `@Custom`) on data class value parameters without use-site target like

```kotlin
// ❌ DOESN'T WORK 
data class Model(
    @Custom(name = "example", value = "property value")
    val property: String,
)
```

processor won't produce "example" property in this case
use-site `get` target must be set to make it work

```kotlin
// ✅ DOES WORK
data class Model(
    @get:Custom(name = "example", value = "property value")
    val property: String,
)
```

**Comment by f1qwase** [comment]
Thanks
I think documenting this point may save some time for other developers in a future
