### ISSUE TITLE
Missing source file and line in the error messages from kapt

### ISSUE THREAD

**Issue by IvanPizhenko** [javalin/javalin-openapi#95]
Example:
```
Cannot add @io.javalin.openapi.OpenApiContent(properties={}, format="-- This string represents a null value and shouldn't be used --", type="-- This string represents a null value and shouldn't be used --", mimeType="AUTODETECT - Will be replaced later", from=io.javalin.openapi.NULL_CLASS), OpenApi generator cannot find matching mime type
```
It would be very helpful if it would output `FILENAME:LINE: error: rest of error message`, where `FILENAME:LINE` corresponds to file and line where that `OpenApiContent` is located.

**Comment by dzikoysk** [comment]
Hmm I need to take a look on the "API". It's basically just a couple of interfaces on top of the raw compiler implementation, but in theory it should be possible to find position in source.
