### ISSUE TITLE
List of OneOf/AllOf/AnyOf

### ISSUE THREAD

**Issue by f1qwase** [javalin/javalin-openapi#96]
We use sealed interfaces in our api and one of the property contains list of entity of sealed interface. This can be expressed in OpenAPI spec using array and oneOf
For example
```kotlin
sealed interface Result

data class Ok (
    val data: String,
) : Result 

data class Error(
    val detail: String,
) : Result


data class Response(
    val results: List<Result>
)
```
can be described as 

```yaml
Response:
    type: object
    properties:
        results:
            type: array
            items:
                $ref: '#/components/schemas/Result'
Result:
    oneOf:
        - $ref: '#/components/schemas/Error'
        - $ref: '#/components/schemas/Ok'
# Error, Ok...
```

is there a way to generate such OpenAPI spec now?
I would suggest to make OneOf annotation appliable to a class:

```kotlin
@OneOf(Ok::class, Error::class)
sealed interface Result

data class Ok (
    val data: String,
) : Result 

data class Error(
    val detail: String,
) : Result


data class Response(
    val results: List<Result>
)
```

what do you think?

**Comment by dzikoysk** [comment]
Currently it's not possible, we'd need to add combinator support in type schema generator:

* https://github.com/javalin/javalin-openapi/blob/main/openapi-annotation-processor/src/main/kotlin/io/javalin/openapi/processor/TypeSchemaGenerator.kt#L43

Does this `oneOf` usage is compatible with OpenApi specification?

**Comment by dzikoysk** [comment]
Yes it is, so I think we should support this:

* https://swagger.io/specification/#schema-object
